### ISSUE TITLE
Do something with refs/objects.Rmd

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/r-novice-inflammation#107]
This was created back before the new lesson-template. If we want to keep it, we should:

*  Rename it as a supplemental lesson and move it to the base directory.
*  Format it according to the new lesson-template.
*  Add it to index.md

**Comment by dhaine** [comment]
It is already covered by 01-supp-data-structures. I'm sending a separate PR for removing it (and its directory).

**Comment by jdblischak** [comment]
I can't find the PR for this.

**Comment by dhaine** [comment]
Think I forgot to do the PR
