### ISSUE TITLE
Change figures/ to fig/

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/r-novice-inflammation#11]
The subdirectory with images is currently `figures/`. This needs to be changed to `fig/`. Also the knitr chunk options at the beginning of each file needs to be updated to reflect this, e.g. `opts_chunk$set(fig.path = "figure/02-func-R-")` would be changed to `opts_chunk$set(fig.path = "fig/02-func-R-")`. See [Lesson Layout][layout] for more information.

[layout]: https://github.com/swcarpentry/lesson-template/blob/gh-pages/LAYOUT.md#code-data-and-figures

**Comment by jameshiebert** [comment]
Shouldn't this be closed by https://github.com/swcarpentry/r-novice-inflammation/pull/23 ?

**Comment by jdblischak** [comment]
I also wanted to have a default option. Thus if someone created a new file and didn't specifically label the output figures, they would still be sent to fig/.

**Comment by jdblischak** [comment]
OK, I made the change to tools/chunk-options.R in lesson template ([PR][]), so this will be fixed once we merge the core branch of lesson-template into this repo. Thanks for the reminder, @jameshiebert.

[PR]: https://github.com/swcarpentry/lesson-template/pull/147
