### ISSUE TITLE
05 cmdline

### ISSUE THREAD

**Issue by erex** [swcarpentry/r-novice-inflammation#130]
For people using Windows, there is no mention of "R" being in the path before making calls to Rscript.  If Rscript is called from the command line without R in the path, lesson 5 will only state that the command "Rscript" cannot be found,

Is there somewhere in the setup instructions that flags up the alteration of the PATH statement to include "R" before this lesson is undertaken?

**Comment by jdblischak** [comment]
For our workshops, we give our learners the following [setup instructions](https://swcarpentry.github.io/workshop-template/index.html#setup) ([source](https://github.com/swcarpentry/workshop-template/blob/gh-pages/index.html#L283)). After installing R and Git Bash, they are instructed to run the  [Software Carpentry Windows installer](https://github.com/swcarpentry/windows-installer). This add R and Rscript to their PATH.

To make it easier for online, self-directed learners to use our lessons, there has been an effort recently to include a "Getting Ready" box on the index page. As an example, see [the index page of the Python lesson](https://swcarpentry.github.io/python-novice-inflammation/). For the formatting, see the [index page of lesson-example](https://github.com/swcarpentry/lesson-example/blob/b480873bec1aaa6dbe57ac1e32b8dd26e484d323/index.md#L12). I'd welcome a Pull Request that creates a "Getting Ready" box that includes a link to the installation instructions.

**Comment by erex** [comment]
Thanks for the pointers to the Installer; my error that because we weren't doing anything with Python nor with Sql, I skipped over the "Adds R's bin directory to the path (if we can find it)" step.

**Comment by jdblischak** [comment]
@erex, are you interested in sending a PR that creates a "Getting Ready" box?
