### ISSUE TITLE
Functional programming example in "Creating functions"?

### ISSUE THREAD

**Issue by arthur-e** [swcarpentry/r-novice-inflammation#136]
In version 5.3 of "Creating functions," there is a great example of function composition for converting temperature from Fahrenheit to Celsius.

```{r}
fahr_to_celsius <- function(temp) {
  temp_k <- fahr_to_kelvin(temp)
  result <- kelvin_to_celsius(temp_k)
  return(result)
}

# freezing point of water in Celsius
fahr_to_celsius(32.0)
```

However, it seems much easier and perhaps more common to use a functional approach and chain the two functions together, at least for the simple purpose described:

```{r}
kelvin_to_celsius(fahr_to_kelvin(32.0))
```

Is there merit to showing both approaches?

**Comment by jdblischak** [comment]
Thanks for the suggestion, @arthur-e. I believe a more verbose option of writing the function was chosen to make it easier for the learners to understand how the two functions were being combined to create a new one, especially for the section on the [the call stack](http://swcarpentry.github.io/r-novice-inflammation/02-func-R.html#the-call-stack). However it is useful to know that functions can be chained together. Would you like to add a callout box to this lesson to demonstrate this point? If yes, please see the [layout instructions](https://github.com/swcarpentry/lesson-example/blob/gh-pages/LAYOUT.md#topics) for the formatting details and the [contributing guidelines](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/CONTRIBUTING.md) for this repo.

**Comment by mfoos** [comment]
I'm working on this!

**Comment by mfoos** [comment]
#192

**Comment by chendaniely** [comment]
closing this PR because of #192 and #196
