### ISSUE TITLE
Add motivational slides

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/r-novice-inflammation#14]
Need to add a 3 minute slideshow to motivate learning R. The instructions are [here][format] and a template is [here][template].

[format]: https://github.com/swcarpentry/lesson-template/blob/gh-pages/LAYOUT.md#motivational-slides
[template]: https://github.com/swcarpentry/lesson-template/blob/gh-pages/motivation.md

**Comment by gvwilson** [comment]
Feel free to reassign.

**Comment by jdblischak** [comment]
Fixed by PR #75.
