### ISSUE TITLE
Misleading wording in 02-func-R

### ISSUE THREAD

**Issue by mxtthias** [swcarpentry/r-novice-inflammation#146]
The first Tip in the file starts with this sentence:

"One feature unique to R is that the return statement is not required."

This feature is far from unique to R. So called "implicit returns" are found in a variety of languages, Erlang, Ruby, and Rust are just three examples.

I would prefer something like "In R, it is not necessary to include the return statement."

**Comment by jdblischak** [comment]
Thanks for the suggestion, @mxtthias. Would you be able to submit a Pull Request with your suggested change made to the file 02-func-R.Rmd?

**Comment by mxtthias** [comment]
@jdblischak: Created https://github.com/swcarpentry/r-novice-inflammation/pull/147

**Comment by jdblischak** [comment]
Fixed by #147.
