### ISSUE TITLE
Add discussion.md

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/r-novice-inflammation#16]
See [here][] for directions. [notes.txt][] may contain some info to be included in this page. Once useful information has been extracted from notes.txt, it can be deleted.

[here]: https://github.com/swcarpentry/lesson-template/blob/gh-pages/LAYOUT.md#discussion-page
[notes.txt]: https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/notes.txt

**Comment by gvwilson** [comment]
Feel free to reassign.

**Comment by jdblischak** [comment]
It's not that substantial, but we do have one now.
