### ISSUE TITLE
car-speeds.csv?

### ISSUE THREAD

**Issue by kallisons** [swcarpentry/r-novice-inflammation#162]
I was going through the 01-supp-read-write-csv.html lesson, but I could not find a link to download the car-speeds.csv.  Also, the file was not in the data folder in r-novice-inflammation-data.zip.  

Could a copy of car-speeds.csv be put in the data folder in r-novice-inflammation-data.zip?

Thanks!

**Comment by marcsze** [comment]
Umich will be working on this

**Comment by pschloss** [comment]
Hey @chendaniely we think we've addressed this issue, can you take a look?

**Comment by chendaniely** [comment]
fixed with #191
