### ISSUE TITLE
Column headers

### ISSUE THREAD

**Issue by arokem** [swcarpentry/r-novice-inflammation#163]
Since we're using data frames, would it make sense to add column headers to the data?

**Comment by chendaniely** [comment]
Not sure. This lesson did start off as a direct translation of the Python lesson.

We already discuss how each row is a patient, and each column is a time point.
Is adding columns to improve the quality of the data?
The columns would almost be the same as the default `R` column names of `V1...V40`

**Comment by hdashnow** [comment]
It does seem a tad pointless with such a simple data set, but I do like this idea to promote good data management in R. So if we were to do this, perhaps discuss why in the lesson.

**Comment by Raphaelaggio** [comment]
I agree. It would be a good idea to have column names replaced perhaps by "T1, T2, T3, ...". I am happy to work on that and add a little discussion of why.

**Comment by chendaniely** [comment]
this is partially addressed in #283 as well (please see that PR for comments).

Since our data have column names we can perhaps close this issue?

**Comment by katrinleinweber** [comment]
Because the related PR was also closed, and this discussion hasn't progressed, I'm going to close this. Please feel free to send another PR from a branch that is based off of current `master`.
