### ISSUE TITLE
Not best practice in the final inflammation example

### ISSUE THREAD

**Issue by arohl** [swcarpentry/r-novice-inflammation#169]
In lesson 4, when the students get their R program to the point where they have a single command to generate all the plots, there is a bit of a problem. If they run the script a second time, they open the newly created pdf documents as well as the csv files and the csv reader gets a little upset being given a pdf file ;-)

In the example before this, where they run a command to generate the plot, the plot is put in the top level directory of the exercise and the data is in the data subdirectory. When they go to automating this, the example reads the cvs file from the data subdirectory and then also writes the pdf to the same directory. My fix (and I am no R programmer!) was to get the automatic program to read the csv filenames **without** the path, do the substitution to create the pdf filename and then prepend *data/* to the csv filename, which results in the PDF files all being in the working directory, whilst reading the cvs from the data subdirectory. Another alternative would be to make sure that only filenames with *inflammation* and *csv* are opened. I leave it to the experts to decide which is preferable.

  Andrew

As an aside, a very nasty result of the R program is that if in the string replacement, the student mistypes csv (e.g. as cvs), all of their input files are clobbered as the pdf filename is the same as the csv filename i.e. they write to the input file - the first solution above will also fix that!

**Comment by hdashnow** [comment]
Is this fully resolved by #189 and #212? Shall I close this issue?

**Comment by arohl** [comment]
Yes, please close

**Comment by hdashnow** [comment]
Ta
