### ISSUE TITLE
Use Pull Request template to ensure that only Rmd file gets submitted

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/r-novice-inflammation#180]
I'm wondering if we could use the new PR templating system that GItHub now provides (https://github.com/blog/2111-issue-and-pull-request-templates) to indicate that only Rmd files should be (normally) submitted when editing one of the lessons.

**Comment by naupaka** [comment]
+1 for this idea.

**Comment by gvwilson** [comment]
I like it too - I'll bring it to the lesson maintainers and see if they 
approve.  An actual template would speed that process along (hint, hint).
