### ISSUE TITLE
Typo in Lesson 1 setwd function call

### ISSUE THREAD

**Issue by pschloss** [swcarpentry/r-novice-inflammation#183]
The lesson currently has:

    setwd("~/Desktop/r-novice-inflammation/)

It should be...

    setwd("~/Desktop/r-novice-inflammation/")

**Comment by pschloss** [comment]
@chendaniely I *think* I filed a PR for this back in February, can I get it merged?

**Comment by chendaniely** [comment]
@pschloss merging!

**Comment by hdashnow** [comment]
Thanks! Fixed by merging #184
