### ISSUE TITLE
Reformat callout boxes

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/r-novice-inflammation#20]
The lessons currently have asides which start with **Tip:**. These need to be reformatted to conform with the new lesson template, see [here][].

To find all the occurrences of these asides, you can run `grep Tip: *Rmd`

[here]: https://github.com/swcarpentry/lesson-template/blob/gh-pages/LAYOUT.md#topics

**Comment by ateucher** [comment]
I've opened a pull request (#32) for this, but have just done the first file. You can wait to merge until I add more commits...

**Comment by ateucher** [comment]
Closed by #32.
