### ISSUE TITLE
Inconsistent challenge naming

### ISSUE THREAD

**Issue by hdashnow** [swcarpentry/r-novice-inflammation#208]
Some challenge titles are pre-pended with "Challenge - ". This is applied inconsistently, and seems to be absent from other lessons in other languages.

e.g. in `01-starting-with-data.Rmd`
```> ## Loading data with headers {.challenge}```
vs
```> ## Challenge - Assigning values to variables {.challenge}```

I suggest removing all "Challenge - ". Any objections?
ping @chendaniely

**Comment by chendaniely** [comment]
Yes, the word "Challenge" in the title should be removed.
Should I fix this before the lesson get's published?

**Comment by gvwilson** [comment]
Yes please - I thought I'd caught them all.  Please make sure you're 
working against the gh-pages branch of gvwilson's repo.

**Comment by chendaniely** [comment]
@gvwilson I was looking at swcarpentry/r-novice-inflammation, Just went though the repo under your account.  This issue seems resolved.
