### ISSUE TITLE
Add Challenge format info to PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by hdashnow** [swcarpentry/r-novice-inflammation#213]
Add some text to PULL_REQUEST_TEMPLATE to deal with common mistakes when submitting challenges, especially:
- Challenge title
- Answer format

Maybe just give a challenge template? Here's a "correct" example to help formulate this template.

``````
> ## Slicing and re-assignment {.challenge}
>
> Using the inflammation data frame `dat` from above:
> Let's pretend there was something wrong with the instrument on the first five days for every second patient (#2, 4, 6, etc.), which resulted in the measurements being twice as large as they should be.
>
> 1. Write a vector containing each affected patient (hint: `? seq`)
> 2. Create a new data frame with in which you halve the first five days' values in only those patients
> 3. Print out the corrected data frame to check that your code has fixed the problem
>

``` {r slicing-re-assignment-answer, eval=FALSE, include=FALSE}
whichPatients <- seq(2,40,2)
whichDays <- c(1:5)
dat2 <- dat
dat2[whichPatients,whichDays] <- dat2[whichPatients,whichDays]/2
(dat2)
```
``````

Not sure if I should hold off on this until the new lesson template is done?

**Comment by gvwilson** [comment]
Should we add something globally as part of the new styles?

**Comment by hdashnow** [comment]
Will it be different for the R lessons c.f. the other languages? If you can make a universal format, then yes please! Presumably then all lessons could have a default PR template, then could add specific lines for their needs (e.g. editing Rmd vs md)

**Comment by hdashnow** [comment]
Update, with the new lesson template, the challenges/solutions should now be formatted like this:

```
> ## Slicing and Re-Assignment
>
> Using the inflammation data frame `dat` from above:
> Let's pretend there was something wrong with the instrument on the first five days for every second patient (#2, 4, 6, etc.), which resulted in the measurements being twice as large as they should be.
>
> 1. Write a vector containing each affected patient (hint: `? seq`)
> 2. Create a new data frame with in which you halve the first five days' values in only those patients
> 3. Print out the corrected data frame to check that your code has fixed the problem
>
> > ## Solution
> > ~~~
> > whichPatients <- seq(2,40,2)
> > whichDays <- c(1:5)
> > dat2 <- dat
> > dat2[whichPatients,whichDays] <- dat2[whichPatients,whichDays]/2
> > (dat2)
> > ~~~
> > {: .r}
> {: .solution}
{: .challenge}```

**Comment by fmichonneau** [comment]
+1 for adding an example of the correctly formatted challenge/solution in the PR template. We can however show how to use it with knitr chunks instead of processed Markdown. It will probably be easier/more familiar to the contributors:

```
> ## Slicing and Re-Assignment
>
> Using the inflammation data frame `dat` from above:
> Let's pretend there was something wrong with the instrument on the first five days for every second patient (#2, 4, 6, etc.), which resulted in the measurements being twice as large as they should be.
>
> 1. Write a vector containing each affected patient (hint: `? seq`)
> 2. Create a new data frame with in which you halve the first five days' values in only those patients
> 3. Print out the corrected data frame to check that your code has fixed the problem
>
> > ## Solution
> > ```{r}
> > whichPatients <- seq(2,40,2)
> > whichDays <- c(1:5)
> > dat2 <- dat
> > dat2[whichPatients,whichDays] <- dat2[whichPatients,whichDays]/2
> > (dat2)
> > ```
> {: .solution}
{: .challenge}
```

**Comment by hdashnow** [comment]
@fmichonneau good idea. Also then the code will run, so output will be included. This is useful for when we're accepting new challenges/solutions and we can check that the answer actually works! (this is not a given as I have discovered). We can always edit it ourselves to turn off the eval=F if needed on a case by case basis.

**Comment by katrinleinweber** [comment]
Since we have many correctly formatted challanges in the episode files, @diyadas and me want to refrain from duplicating one of them into another file. We'll encourage contributors to use other episode files as examples.
