### ISSUE TITLE
Write motivating questions for episodes

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/r-novice-inflammation#219]
The motivating questions for the lesson episodes need to be written.

**Comment by hdashnow** [comment]
@gvwilson, shall I PR these on https://github.com/gvwilson/r-novice-inflammation, so we can see the result live?

**Comment by gvwilson** [comment]
Yes please (the gh-pages branch), and thank you very much.

**Comment by gvwilson** [comment]
Please review additional questions in 85fcbbd4152c6.

**Comment by hdashnow** [comment]
I didn't notice any different questions, maybe not the right diff? Or do you mean the key points? A few minor comments, but otherwise looks excellent to me!
