### ISSUE TITLE
Make sure all lessons have objectives and keypoints

### ISSUE THREAD

**Issue by hdashnow** [swcarpentry/r-novice-inflammation#221]
Many lessons are missing keypoints in the yaml header of the Rmd files. One is also rather thin on objectives.

Objectives will be shown at the start of a lesson, to let participants know what to expect. Key points will appear at the end of the lesson, as a checkpoint so participants can check their understanding.

**The following lessons are missing Key points:**
(note these lesson numbers are might change again with the new lesson template, so use the titles if unsure)

**Main lessons:**

- [ ] 06 Best Practices for Writing R
- [ ] 07 Dynamic Reports with knitr
- [ ] 08 Making Packages in R (also objective is there, but possibly too brief?)

**Supplementary lessons:**

- [ ] 09 Introduction to RStudio
- [ ] 10 Addressing Data
- [ ] 13 Data Types and Structures
- [ ] 14 The Call Stack
- [ ] 15 Loops in R

Here's an example of what it should look like:
```
---
title: "Analyzing Multiple Data Sets"
teaching: 30
exercises: 0
questions:
- "How can I do the same thing to multiple data sets?"
- "How do I write a `for` loop?"
objectives:
- "Explain what a `for` loop does."
- "Correctly write `for` loops to repeat simple calculations."
- "Trace changes to a loop variable as the loop runs."
- "Trace changes to other variables as they are updated by a `for` loop."
- "Use a function to get a list of filenames that match a simple pattern."
- "Use a `for` loop to process multiple files."
keypoints:
- "Use `for (variable in collection)` to process the elements of a collection one at a time."
- "The body of a `for` loop is surrounded by curly braces (`{}`)."
- "Use `length(thing)` to determine the length of something that contains other values."
- "Use `list.files(path = \"path\", pattern = \"pattern\", full.names = TRUE)` to create a list of files whose names match a pattern."
---
```

**Comment by gvwilson** [comment]
Please review the keypoints added in 85fcbbd4152c6.
