### ISSUE TITLE
Check/remove unexpected images

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/r-novice-inflammation#222]
`make lesson-check` reports:

Unexpected image files: 01-supp-factors-adjusting-levels-1.png, 01-supp-factors-dropping-levels-1.png, 01-supp-factors-gender-counts-1.png, 01-supp-factors-reordering-factors-1.png, 01-supp-factors-updating-factors-1.png, 02-func-R-rescale-test-1.png, 02-func-R-rescale-test-2.png, 03-loops-R-loop-analyze-5.png, 03-loops-R-loop-analyze-6.png, 03-loops-R-loop-analyze-7.png, 03-loops-R-loop-analyze-8.png, 03-loops-R-loop-analyze-9.png, logical_vectors_indexing2-1.png, python-operations-across-axes.svg

**Comment by chendaniely** [comment]
on b4efb47e8a399b25b3d16fc1bab8930c9d048b7a i see:

```
...
Unexpected image files: rmd-02-func-R-rescale-test-1.png, rmd-02-func-R-rescale-test-2.png
```

**Comment by katrinleinweber** [comment]
On https://github.com/swcarpentry/r-novice-inflammation/commit/faf11b4e3cd8bdb0d06b709669be3fd9d302d3ba I see: `R-package-structure.svg, arithmetic-variables.svg, memory-variables.svg, new-variables.svg, reassign-variables.svg, rmd-02-func-R-rescale-test-1.png, rmd-02-func-R-rescale-test-2.png, tag-variables.svg`

**Comment by katrinleinweber** [comment]
Related to #217?

**Comment by diyadas** [comment]
This seems to have been resolved at some point. make lesson-check reports other errors, but not this one.
