### ISSUE TITLE
Fix errors in new-format episodes

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/r-novice-inflammation#224]
Several of the episodes in #223 have errors due to @gvwilson's lack of R skillz. Look for `.error` in `_episodes/*.md` to find them, then trace back to the `_episodes_rmd/*.Rmd` file to fix.

**Comment by hdashnow** [comment]
@gvwilson the remaining errors (after @fmichonneau's fix) are all deliberate 😄

**Comment by fmichonneau** [comment]
do we still need a PR that removes the PDF files from the data folder, or has it been taken care of?

**Comment by gvwilson** [comment]
I believe it's been taken care of.

Thanks,

Greg


On 2016-07-11 10:53 AM, Francois Michonneau wrote:
>
> do we still need a PR that removes the PDF files from the data folder, 
> or has it been taken care of?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/swcarpentry/r-novice-inflammation/issues/224#issuecomment-231758614>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AA3ozsctUopowfp5GCZ94ivjQJ1f6hCjks5qUljegaJpZM4JImTk>.
>

-- 
Dr Greg Wilson
Director of Instructor Training
Software Carpentry Foundation
