### ISSUE TITLE
02-func-R solution for outside() not displayed on lesson

### ISSUE THREAD

**Issue by ytakemon** [swcarpentry/r-novice-inflammation#257]
While following the [second lesson](http://swcarpentry.github.io/r-novice-inflammation/02-func-R/) under Create a Function, I noticed that there was no solution for creating a function called outside(). However on your [Rmd file](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/_episodes_rmd/02-func-R.Rmd) for this lesson there is a solution for creating outside(). Perhaps this is an update issue?

**Comment by katrinleinweber** [comment]
Dear @ytakemon, thanks for this hint, and my apologies that this was left alone for so long.
