### ISSUE TITLE
Framing the lesson: "Interactive programming"

### ISSUE THREAD

**Issue by pcarbo** [swcarpentry/r-novice-inflammation#259]
This lesson is framed as an "introduction to basic concepts in programming", but this isn't quite correct; I would instead say that this is an introduction to *interactive programming*, or more specifically, *programming in an interactive environment*. This contrasts with the non-interactive programming setting which typically involves (1) writing code, (2) compiling the code, (3) building and/or linking the executable, and (4) running the executable.

Framing the lesson in this way would also help to clarify some of the concepts introduced, as well as the lesson goals. For example, the first aim of the first episode is to load the data (which currently exists as a file on your computer) *as a variable in the R environment*.

To take another example, the lesson objective, "Read tabular data from a file into a program" can be rewritten more precisely as "Read tabular data from a file into the R environment"; the term "program" is ambiguous because it could refer to either the R software itself or code that is run in R (e.g., using Rscript), which is technically a program as well.

I hope this doesn't sound pedantic---I firmly believe that using terms such as "interactive programming" and "R environment" will make the lessons more clear, and I don't think requires much modification to the existing description. This clarity is especially important for an R beginner who is already familiar with a language such as C or Java. (Note that my comments apply to the Python lesson as well, but I raised the issue here because I am much more familiar with R.)

**Comment by naupaka** [comment]
Yes, fully agree. Precision is key and it's easier to have mentioned it correctly from the beginning so that if/when you do get to explaining it later students have been exposed to it. Why don't you submit a PR with your proposed wording changes and we can take it from there?

**Comment by pcarbo** [comment]
Sounds good! I will work on this.

**Comment by katrinleinweber** [comment]
Hello @pcarbo, have you considered addressing this issues with a PR? It has been a while ;-)

**Comment by katrinleinweber** [comment]
Accepted. No worries :-)
