### ISSUE TITLE
unittests with the _testthat_ package

### ISSUE THREAD

**Issue by sluedtke** [swcarpentry/r-novice-inflammation#265]
Hi  there, 

while scanning through the r-novice-inflammation material I was wondering if it was useful to add a part on __unittests__ using a dedicated package (e.g. 'testthat').

I think it might fit or link with two already existing topics, namely [Creating functions](http://swcarpentry.github.io/r-novice-inflammation/02-func-R/)  and [Making packages in R](http://swcarpentry.github.io/r-novice-inflammation/08-making-packages-R/). Especially the first one introduces tests of functions but does not show a  convenient way to use them.

What's your opinion about that?

**Comment by bbolker** [comment]
Definitely an advanced/supplementary topic IMO.  I don't know how people are using this material (maybe they're teaching to more advanced audiences and skipping the intro stuff), but given that according to the instructor notes it takes two half-day sessions to teach the material in episodes 1-5, it's hard to see anyone getting as far as unit tests ... in a vanilla/introductory Software Carpentry workshop.

I'm pretty ignorant/inexperienced, so take my comments with the appropriate grain of salt.

**Comment by sluedtke** [comment]
I am just starting with software carpentry so I do not have any experience but agree that it's quite a lot of stuff already. Because it is quite a lot, I think that not everything is thought in a single sequence but rather that certain episodes are picked with respect to the demands of the workshop. 

Maybe more experienced instructors have an opinion about that.
 
Ignoring the quantity of the existing R-material, I think that 'Making packages in R' has to have a section on unit tests. If we want to encourage people to make reproducible and reliable code that might be shared with others, unit tests are an essential part to ensure that.

**Comment by chendaniely** [comment]
thanks @sluedtke for raising the issue.

I usually show the `expect_*` class of functions relatively early.
People will usually `print` or `View` the loaded data to visually check values.
I typically have them write the `testthat` statement to check that the value is what they expect.

This helps them use the unittest functions without the overhead of running unittests.

You can always add it in at the end if there's time in the workshop, so it would be a topic we can put in the `extras` part of the lesson

**Comment by sluedtke** [comment]
We are currently preparing an SC workshop and we realy want to add some parts from the `testthat` package. 

We'll stick to the functions that are used as examples and challenges and adding tests about them.

So I think that quite follows the suggestions or workflow by @chendaniely, but formalising things most people do anyway to check their code (e.g. `print` ).

As soon as it is ready I'll drop a line and we see how it might be integrated or not.

**Comment by katrinleinweber** [comment]
Hello, and thanks for bringing this topic into the discussion :-)

While I agree that `testthat` is extremely useful, I think for now, mentioning it and referring people to [exercism.io](http://exercism.io/languages/r/about) (see , see https://github.com/swcarpentry/lesson-example/issues/163) would be effective than to integrate teaching about tests here.

After #324 (or as part of it), teaching `testthat` would be worthwhile in the long run.

**Comment by katrinleinweber** [comment]
@sluedtke @bbolker @chendaniely I'm working on this in https://github.com/TIBHannover/FAIR-R/pull/1 for a Carpentries-based workshop. Please feel free to test and comment there. After that workshop, it might be worth merging at least a few of the updates back in here.

**Comment by katrinleinweber** [comment]
Hi @sluedtke,

Please have a look at https://tibhannover.github.io/FAIR-R/05-testthat/ where a condensed, advanced variant of this lesson has been developed. It emphasises function docu, packaging and testing. We'll therefore probably not include a lot of it here.

Thus, I'm going to close this.

Kind regards,

Katrin
