### ISSUE TITLE
days and patients swapped in solution for "Slicing and Re-Assignment"

### ISSUE THREAD

**Issue by harmn** [swcarpentry/r-novice-inflammation#279]
Please delete the text below before submitting your contribution. 

In lesson 1, in the solution for "Slicing and Re-Assignment" the days and patients are swapped
http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/

This should be the solution:
whichPatients <- seq(2,60,2)
whichDays <- c(1:5)
dat2 <- dat
dat2[whichPatients, whichDays] <- dat2[whichPatients, whichDays]/2
(dat2)

**Comment by katrinleinweber** [comment]
Hi @harmn! This was fixed by [#287](https://github.com/swcarpentry/r-novice-inflammation/pull/287/files), but not auto-closed by a [commit keyword](https://help.github.com/articles/closing-issues-using-keywords/) ;-)
