### ISSUE TITLE
Forcing Conversion discussion

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/r-novice-inflammation#290]
in #255 @plantarum removed (commented out) the section on `Forcing Conversion`.

Instead of discussing the use or `as.numeric` before performing `mean`.
Should we just use the `rowMeans` function?
This way we can show the behavior, without having to do the type conversion.

**Comment by katrinleinweber** [comment]
Because `rowMeans` is included in https://github.com/swcarpentry/r-novice-inflammation/blame/9c9198f5ce2f3f0ab073bd2276ded9aaa374ee55/_episodes/01-starting-with-data.md#L812 This discussion seems to have resolved itself over time. Please reopen if I understood the gist of this issue incorrectly.
