### ISSUE TITLE
Subsetting data frames by names also possible for rows

### ISSUE THREAD

**Issue by gosianow** [swcarpentry/r-novice-inflammation#295]
In Programming with R, Addressing Data, there are three ways of addressing data frames in R:
- By index (slicing),
- By logical vector,
- By name (columns only).

Using `$` works only for columns, but subsetting by names using `[]` is possible for both rows and columns, for example, `head(dat['2', c('Age', 'Gender')])`. So maybe the last point should be rephrased to something like this: "By name ($ for columns only)"? And an example of subsetting by row names could be added? 

The order of the content is:
- Addressing by Index
- Addressing by Name
- Logical Indexing

Maybe it could be put in the same order as the first list, or the first list could be reordered.

The function `names` is presented. Maybe it is worth presenting also `colnames` and `rownames`?

**Comment by katrinleinweber** [comment]
Hello @gosianow! Thanks for taking the time to submit this suggestion :-)

I agree about `presenting also colnames and rownames`, see #315. could I interest you in submitting a PR with that change, and a second one for the subsetting?

**Comment by taddallas** [comment]
I believe this issue can be closed.

**Comment by HaoZeke** [comment]
Thanks @taddallas.
