### ISSUE TITLE
Change of class for data frame subsets by column

### ISSUE THREAD

**Issue by gosianow** [swcarpentry/r-novice-inflammation#296]
In Programming with R, Addressing Data, there is a line of code that shows the class of `dat`:
`class(dat)`
which is a `"data.frame"`. Maybe just for completeness, it would be worth mentioning that when subsetting by column, the class of what we get changes. For example, for `dat$Gender`
`class(dat$Gender)` is `"character"`.

**Comment by katrinleinweber** [comment]
As in #295, please feel free to send a PR. Your suggestion makes sense, so I'd be happy to review a specific "implementation" / addition to the lesson :-)
