### ISSUE TITLE
Typo in chapter 06-best-practices-R: 'exits' instead of 'exists'

### ISSUE THREAD

**Issue by luiandresgonzalez** [swcarpentry/r-novice-inflammation#299]
There is this piece of text under the "Be careful when using `setwd()`" section:

> `setwd()` will return an error if the directory to which you’re trying to change doesn’t **exit**...

I think it is meant to say "exists". 

Thanks for the good work!

**Comment by katrinleinweber** [comment]
Merged :-) Thanks for also alerting us to this!
