### ISSUE TITLE
Analyzing Multiple Data Sets : Challenge

### ISSUE THREAD

**Issue by Jerry-Lai** [swcarpentry/r-novice-inflammation#305]
**Challenge: Using Loops to Analyze Multiple Files**

**Current Version**
analyze_all <- function(pattern) {
  filenames <- list.files(path = "data", pattern = pattern, full.names = TRUE)
  for (f in filenames) {
    analyze(f)
  }
}

**Proposed Version: Two Input Parameters**
analyze_all <- function(**_folder_**, pattern) {
  filenames <- list.files(path = **_folder_** , pattern = pattern, full.names = TRUE)
  for (f in filenames) {
    analyze(f)
  }
}

I think the proposed version is only slightly more complex than the current version, conceptually speaking; but useful practically.
Also, it fits well with the more complex "function writing" examples from earlier modules, where two parameters were involved.

**Comment by katrinleinweber** [comment]
Thanks for taking the time make this suggestion, @Jerry-Lai :-)   I agree, and would be happy to review a PR of yours that implements this change. Please note that you can use [commit keywords](https://help.github.com/articles/closing-issues-using-keywords/) to automatically close this issue from within the PR ;-)
