### ISSUE TITLE
Teach roxygen2 skeleton instead of free-form comments

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#309]
Hello!

Since the function comments in [lesson 2](http://swcarpentry.github.io/r-novice-inflammation/02-func-R/) & [3](http://swcarpentry.github.io/r-novice-inflammation/03-loops-R/) cover two thirds of the [roxygen2 skeleton](https://cran.r-project.org/web/packages/roxygen2/vignettes/rd.html) `@param`, `@return` & `@examples`, I wonder whether it would be worthwhile to shift the teaching to that standard and relegate the unstructured docu examples to the interactive / script-like lesson content?

What do you think?

Cheers :-)

PS: A little side effect on the lesson would be the need to upgrade "we often use RStudio, but it is not required" to an _actual_ prerequisite, because of the `Shift+Alt+Cmd+R` shortcut / code tool.

**Comment by katrinleinweber** [comment]
PPS: Reading "[Good enough practices in scientific computing > What we left out > Documentation](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510#sec027)", I wand to add to the above:

> […] in practice, people won't write comprehensive documentation until they have collaborators who will use it.

OK, same thing whether they _don't_ fill out the roxygen2 skeleton, or whether they _don't_ write a few lines of unstructured comments.

> They will, however, quickly see the point of a brief explanatory comment at the start of each script, so we have recommended that as a first step.

And at that point, teaching that RStudio shortcut and filling out `@param`, `@return` & `@examples` seems to cover exactly the ["good enough practice" **2a**](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510#sec005).

**Comment by lvclark** [comment]
I think it could be a little confusing to students.  They've been told that comments can be entirely free form, but then they are shown that function comments have to follow a certain format, two hours before they are shown the benefit of sticking to that format.

My personal feeling is that roxygen discourages thorough documentation by cluttering up the source code, so I just like to use `prompt` and then fill in the .Rd file manually.  But for beginners I can definitely see the benefit of roxygen providing a quick and easy way to make documentation.  (Perhaps encourage them to take a quick peek at the .Rd file (not just the rendered version) after running `document`?  But that might be another thread.)

**Comment by katrinleinweber** [comment]
> [...] They've been told that comments can be entirely free form

We can still tell them "that's fine _additionally_".

> [...] two hours before they are shown the benefit of sticking to that format.

[Respectfully, I disagree here, because: `help(apply)` & `?apply` being introduced very early](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/_episodes_rmd/01-starting-with-data.Rmd#getting-help) could be used to display the benefit of using a defined comment format right there. Navigating the help pages is rather easy, because their authors adhere to a certain format.

**Comment by katrinleinweber** [comment]
@lvclark: I drafted a larger rewrite about docu and packaging in #360. Please feel free to test & review.

**Comment by katrinleinweber** [comment]
This is getting a bit out of hand. I'll try resetting `08-packaging` and updating it only minimally with the reference to `center.R` & `rescale.R`.

**Comment by katrinleinweber** [comment]
The discussion has moved on in https://github.com/swcarpentry/r-novice-inflammation/pull/360#issuecomment-415345689.
