### ISSUE TITLE
Setting working directory in 01-starting-with-data with tab complete

### ISSUE THREAD

**Issue by ingridstarr** [swcarpentry/r-novice-inflammation#311]
Hi there, 

Getting everybody set up in the correct working directory at the start of this lesson seems to reliably take ~10 minutes (or more...). While the GUI Session -> Set Working Directory -> Choose Directory... method is in the teaching material, I think using tab complete (works in both R and RStudio) makes more sense, as it reinforces the use of tab complete seen in the Unix lesson and also the move away from point and click computer use.

**Comment by katrinleinweber** [comment]
Hello :-) In case you mean tabbing to expand a `setwd(dir = "…")` command, I agree.

**Comment by ingridstarr** [comment]
Yep that's exactly it :)

**Comment by taddallas** [comment]
I believe this issue can be closed.
