### ISSUE TITLE
Suggestion: Introduce length alongside dim in section 1 (Starting with Data)

### ISSUE THREAD

**Issue by diyadas** [swcarpentry/r-novice-inflammation#312]
I find it a bit odd that the `length` command is not introduced in this section, though `dim` is. As I was preparing for my teaching demo, I found myself accidentally referencing it, only to realize it hasn't been taught.

I think it's especially useful to use `length` to check the result of `apply`, which is also taught in this section. Even as an intermediate user, I found myself mixing up the margin when using `apply`, and so doing a quick dimension check was the easiest way to confirm I'd selected the correct axis when working with complex datasets. But because we've created a vector vs. a matrix, `dim` returns NULL. You could demonstrate with `dim(as.matrix(v))` but that seems unnecessarily complex at this point, and `length` is a useful command. It *is* introduced a bit later - in section 3 (loops in R) - but I think it could be very useful here.

**Comment by PLNReynolds** [comment]
I agree that length is a helpful command. I added it to the list of commands, but that might not be the best place as novices are most likely to use for a vectors or factors and not data frame.  But, maybe it should appear even earlier when vectors are first introduced? Discuss?

**Comment by diyadas** [comment]
Closing (my own) issue - having taught the lesson now in a workshop, I don't think it's as big an issue. It's introduced not long after where I'd proposed, and the first episode is already full of information that I wouldn't want to remove.
