### ISSUE TITLE
enhance teaching R terminology by using variable.names() instead of names()

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#315]
Hello!

Did anyone experience confusion of learners about us teaching `names()` for the column headers, while mentioning [`rownames()`](https://github.com/swcarpentry/r-novice-inflammation/search?utf8=%E2%9C%93&q=rownames&type=)? If yes, how about replacing the former with either:

a) `colnames()` to increase consistency, or 
b) `variable.names()` to ingrain R's terminology (in the base package `stats`)?

Technically, they return the same:

```R
> identical(variable.names(dat), names(dat))
[1] TRUE
> identical(variable.names(dat), colnames(dat))
[1] TRUE
```

PS: Unfortunately there is no `observation.names()` alias for `rownames()` :-/

**Comment by diyadas** [comment]
I'd prefer a shift to `colnames` to match `rownames`, which should produce the intended result for both data frames and matrices. `names` doesn't map onto column names for matrices - this can be confusing for learners.
