### ISSUE TITLE
Nonsense sentence in 06 - Best Practices

### ISSUE THREAD

**Issue by lvclark** [swcarpentry/r-novice-inflammation#317]
In Episode 06 - Best Practices, there is the sentence "For example, it's often helpful when writing code to separate the if you create only one or a few custom functions in your script, put them toward the top of your code."  Was something perhaps accidentally deleted here?

**Comment by katrinleinweber** [comment]
Yes, you're right. I stumbled over this as well and we fixed it in #314. Please keep an eye open for other such issues and don't hesitate to also start a PR right away, if it's a small improvement suggestion, and nobody PR'ed or issue'd about before. Cheers :-)
