### ISSUE TITLE
Documentation of data?

### ISSUE THREAD

**Issue by MariekeDirk** [swcarpentry/r-novice-inflammation#321]
Hi there,

I was reading the R lessons 'Making Packages in R' section. I was wondering if it would be an option to add documentation of data to the extra material? My suggestion would be to document, for example, "car-speeds.csv".

Let me know if this would be an option. I'd be happy to help.
Kind regards,
Marieke

**Comment by katrinleinweber** [comment]
Hello :-) Thanks for taking the time to send in your suggestion!

On my first workthrough of [`11-supp-read-write-csv.Rmd`](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/_episodes_rmd/11-supp-read-write-csv.Rmd#read-a-csv-and-explore-the-arguments) I felt that the data was step-by-step sufficiently documented. What do you feel is missing?

I'd be happy to review a PR with your additional docu suggestions :-)

**Comment by MariekeDirk** [comment]
Hi,

Thanks for your comment. I agree that the documentation is good. It's more like an addition to the lesson, see http://r-pkgs.had.co.nz/data.html for an example of the data documentation. I find it quite handy as I sometimes forget what the different columns of my data frame meant. It also makes it easier to share your data with others. 

What do you think?
Kind regards,
Marieke

**Comment by katrinleinweber** [comment]
A PR with that would be a learning opportunity for me, because I haven't had to do this myself so far. I'm curious how it would look for the `car-speeds`.

**Comment by MariekeDirk** [comment]
I've worked out an example and put it on https://github.com/MariekeDirk/r-novice-inflammation.git 

Technically it is not that difficult but there are quite some concepts which need to be introduced in order to make the documentation work. 

In short (within /Vignettes/data_documentations.Rmd I included these steps):
1) Make a Rproject, including DESCRIPTION, NAMESPACE and /R folder (`devtools::create()`)
2) Read the raw-data and use `devtools::use_data()` to make a .rda data file (stored in /data)
3) Document the data within the /R folder under the name data.R
4) Update the package with document, build & reload

I'm new to this, so if you also think it would be useful to include this in extra lesson material how should we proceed?

**Comment by katrinleinweber** [comment]
Thank you!

Yes, how to proceed is a good question. It kinda fits both into [`11-supp...`](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/_episodes_rmd/11-supp-read-write-csv.Rmd#read-a-csv-and-explore-the-arguments) and into [`08-making-packages`](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/_episodes_rmd/08-making-packages-R.Rmd).

For now, I would aim for the former, but start a new issue about improving the documentation / packaging episodes for both functions and data.

**Comment by MariekeDirk** [comment]
Tanks! :)
