### ISSUE TITLE
hard-wrap comments longer than 80 characters to avoid scrolling horizontal scrolling

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#325]
Not in the rendered website, but in GitHub's preview. E.g. https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/_episodes_rmd/11-supp-read-write-csv.Rmd#write-a-new-csv-and-explore-the-arguments

Splitting up all instances of  `# looong comment` into several lines:

    # looong 
    # comment

**Comment by nick-ulle** [comment]
I've submitted a pull request to hard-wrap the comments that are longer than 80 characters.
