### ISSUE TITLE
Image naming

### ISSUE THREAD

**Issue by ateucher** [swcarpentry/r-novice-inflammation#34]
In working on #20, I'm finding that some of the filenames for generated figures are different. For example, in the loops lesson the images created in the loop have a numeric suffix following a hyphen, while previously it seems that there was no hyphen before the numeric suffix.  As a result, there are some orphan images in the /fig folder, and some broken image links in the html and md files where the newly generated images weren't commited (e.g., the last few figures in https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/03-loops-R.md). I'm not sure if this is due to different versions of knitr or rmarkdown, or ... ?

I've commited the newly named image files for that example (in https://github.com/ateucher/r-novice-inflammation/commit/ceb3a798637b98dd9122e072395854e3d15e0ab8) so that the images appear in the md/html files, however I haven't deleted the orphans, as I thought maybe this should be taken on as a broader issue.

**Comment by jdblischak** [comment]
As I mentioned in #20, the difference in numbering is due to a change in knitr. You are welcome to clean out the orphans in your current PR or wait and do it in a separate PR (or have someone else do it).

**Comment by gvwilson** [comment]
Is there some way to force an image name in knitr?  (I've asked for this 
in the IPython Notebook to avoid renaming when figures are moved around.)

**Comment by ateucher** [comment]
Will do, thanks @jdblischak.

**Comment by jdblischak** [comment]
@gvwilson, we force the name of a plot that is generated by a chunk of R code with the chunk option `fig.path`. When more than one plot is generated by a chunk of code, they get numbered. The issue we currently have is that knitr changed how it numbered these multiple figures. We just need to to update everything.

**Comment by ateucher** [comment]
I've cleaned out the orphans in #32, so I think this is taken care of.
