### ISSUE TITLE
Packaging: refer to other resources

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#343]
https://github.com/swcarpentry/r-novice-inflammation/_episodes_rmd/08-making-packages-R.Rmd could use a mention of https://devguide.ropensci.org/building.html (formerly [onboarding.../packaging_guide](https://web.archive.org/web/20171222124034/http://onboarding.ropensci.org/packaging_guide.html)).

**Comment by katrinleinweber** [comment]
Related to #360, because packaging is touched there as well.

**Comment by lauzikaite** [comment]
The suggested link [](https://onboarding.ropensci.org/packaging_guide.html) is no longer valid.

@katrinleinweber, did you mean the rOpenSci book that is now live at [](https://devguide.ropensci.org/)? If so, I can submit a PR shortly.

**Comment by katrinleinweber** [comment]
It's probably https://devguide.ropensci.org/building.html now, at least when compared to https://web.archive.org/web/20171222124034/http://onboarding.ropensci.org/packaging_guide.html

**Comment by lakikowolfe** [comment]
Hey! I was just going through issues to find one to work on as a part of my instructor training. I believe this issue has been resolved in #459 and should be marked as closed.

**Comment by HaoZeke** [comment]
Thanks @lakikowolfe !
