### ISSUE TITLE
New GitHub labels

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/r-novice-inflammation#346]
Hello maintainers

I'd like to deploy the [new GitHub labels](http://www.datacarpentry.org/2018-04-05-github-labels) for this repository in preparation for the Bug BBQ. 

How would like me to deal with existing labels? I can either:
1. only deploy the new labels, the old ones will stay in the repository, and you can take care of the conversion at your convenience
2. deploy the new labels and re-assign labeled issues to the new labels. I'll convert `bug`, `discussion`, `enhancement`, `template and tools` to `type:bug`, `type:discussion`, `type:enhancement`, `type:template and tools` respectively. I'll let you take care of the other labels as needed.

If you prefer to start with a clean slate, I can also delete all existing labels, and deploy the new ones. In this case, note that labels assigned to current issues will be lost.

**Comment by katrinleinweber** [comment]
I prefer to wait and see how the other repos fare. To match the proposed new standard, I already adjusted the colors of `good first issue` & `help wanted` here, but you know my opinion of diverging from the GitHub standard. So, I disagree with any other changes to the labels here.

@diyadas has a vote in this as well.

**Comment by diyadas** [comment]
I do like the move toward splitting tags between type and status. However, I think there's potential for a substantial amount of overlap in the type tags, based on the issues I've seen thus far.

If the new labels are added, I definitely do not want to automatically convert `discussion` to `type: discussion`, etc. Right now, the `discussion` tag is used to indicate that the issue requires discussion (this issue would fall in that category, imo!), which is a different statement than `type: discussion`. I think we should definitely be careful about relabeling older issues.

I'd prefer to wait a bit as well before incorporating the new labels. I'll have more time towards the end of May to focus on relabeling. (I know adding new labels doesn't mandate relabeling immediately, but I do not think it good to have a half old / half new system, especially when `discussion` and `type: discussion` mean such different things.) Perhaps then we'll also have the results from the other repos?

**Comment by fmichonneau** [comment]
@diyadas Could you clarify the difference you see between "discussion" and "type:discussion". The latter is [defined](https://docs.carpentries.org/topic_folders/maintainers/github_labels.html) as:

>  "Issue used to ask a question about how the lesson is taught, ask for clarification. Such issues might indicate that the instructor guide or the documentation may need to be updated."

and is not intended to be different from the old "discussion" label.

The lesson infrastructure committee has approved the common set of labels (https://docs.carpentries.org/topic_folders/maintainers/github_labels.html) across all lesson repositories during its last meeting on May 23rd.

I have been tasked to deploy them, and I'd like to do it soon on this repository. If you still have questions or concerns, please let me [or the committee](https://github.com/carpentries/lesson-infrastructure/issues/1) know. Thanks!

**Comment by diyadas** [comment]
I see the current usage of "discussion" to be broader than "type:discussion" including a meta level of the lesson contribution process, and not just the teaching of the lesson. 

If you're deploying the new labels, please don't convert any of the old ones. I strongly prefer manual retagging on an issue by issue basis to avoid confusion.

Thanks.

**Comment by fmichonneau** [comment]
This repository has now been converted to use the standard set of labels. Existing labels have been preserved.

The lesson infrastructure committee hopes the standard set of labels will make it easier for you to manage the issues you receive on the repositories you manage.

The lesson infrastructure committee will evaluate how the labels are being used in the next few months and we will solicit your feedback at this stage. In the meantime, if you have any questions or concerns, please leave a comment on [this issue](https://github.com/carpentries/lesson-infrastructure/issues/1).

-- The Lesson Infrastructure subcommittee
