### ISSUE TITLE
Item numbering not parsed correctly 

### ISSUE THREAD

**Issue by pauljohn32** [swcarpentry/r-novice-inflammation#348]
If you don't see a quick fix for this minor problem, I'm willing to try to learn your setup so I can help.

On this page, I notice that the enumerated list numbering is broken by the insertion of comments within the items: http://swcarpentry.github.io/r-novice-inflammation/06-best-practices-R.  Look down to the word "rather than".  The next item is numbered incorrectly as "1".  Note that explicitly numbering the item did not help in that case.

This problem is not inherent in pandoc or the Rmarkdown format.  I think there may be a little defect in the document template you are using, maybe something in the code chunk display that provides those bootstrap class (left side highlighted bar) elements. Maybe.  You know more than I do. 

I know this is not inherent because I have an example that does work.  If you take a quick look to verify: http://pj.freefaculty.org/scraps/elistdemo.html.  Just in case it helps (I doubt it does), I attach a zip file that has my Rmd file, template, and HTML output.

[eldemo.zip](https://github.com/swcarpentry/r-novice-inflammation/files/1910584/eldemo.zip)

I have found markdown templates to be frustrating and difficult. If you think this is something I should try to fix in your setup, I will try.  But I agree with you if you say it is not easy...

---
PJ

**Comment by katrinleinweber** [comment]
Hi Paul, thanks for reporting this and for providing the example :-)

This could indeed be tricky to fix in the template or the MD processor... It's a `5.` [in the `.md` file](https://github.com/swcarpentry/r-novice-inflammation/blame/gh-pages/_episodes/06-best-practices-R.md#L125-L133), but a new `<ol><li>` in the `.html`, so Jekyll seems to be the problem.

Although I'm curious for a correct solution to this, maybe a much easier work-around would to convert the first part of each item to an `h4` and the latter to a paragraph below it? They don't _have to be_ in a numbered list, I presume. Just easily recognisable as independent advice.

I'd be happy to review a PR with either solution. In any case, have a nice weekend!

**Comment by pauljohn32** [comment]
I need an idiot's guide.  Is it Jekyll I need to understand?
I know how to convert Rmd -> md -> html, but I don't understand what Jekyll is or what it has to do with this process.

**Comment by diyadas** [comment]
Hi PJ. Jekyll parses the markdown to generate the website (so the MD -> HTML conversion, which is where the issue appears). You can read more about Jekyll [here](https://jekyllrb.com/docs/home/), if you'd like to dive in. However, if that's too much trouble, I think Katrin's workaround would be an equally good solution.

**Comment by pauljohn32** [comment]
I'm starting to understand.  I did not realize that Pandoc was not used for this purpose.  Am in process of installing Jekyll on my laptop so I can test this out.

**Comment by diyadas** [comment]
Thank you for your efforts! It looks like there may actually be a solution in this StackOverflow [post](https://stackoverflow.com/questions/35858704/jekyll-kramdown-code-in-ordered-list-number-reset) but I'm not sure how that will fare in Rmd -> md conversion.

**Comment by katrinleinweber** [comment]
It fares well :-)

About pandoc: we [mention it in the lesson](https://github.com/swcarpentry/r-novice-inflammation/search?utf8=%E2%9C%93&q=pandoc&type=), but don't use it for the website build, except maybe within the `knit`-ing step. My understanding of all this is incomplete as well ;-)

**Comment by katrinleinweber** [comment]
About pandoc: we [mention it in the lesson](https://github.com/swcarpentry/r-novice-inflammation/search?utf8=%E2%9C%93&q=pandoc&type=), but don't use it for the website build, except maybe within the `knit`-ing step. My understanding of all this is incomplete as well ;-)
