### ISSUE TITLE
"Edit..." & "Improve..." quick-links broken

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#357]
Both https://github.com/swcarpentry/r-novice-inflammation/blob/f4684f8d9769a39b4c33dcbe7ad91cbd8c12fa90/_includes/navbar.html#L73 and https://github.com/swcarpentry/r-novice-inflammation/blob/f4684f8d9769a39b4c33dcbe7ad91cbd8c12fa90/_includes/lesson_footer.html#L22 don't actually direct to the corresponding `_episodes_rmd/...Rmd` file. Apparently, ~~`replace` has no effect anymore~~ `{% if page.source == "Rmd" %}` does not trigger as it should.

I think, because `page.source` is always empty. How can we ensure this variable is always either `Rmd` or `md`?

Noticed in #355 & #356. @rgaiacs: ~~Maybe related to #350?~~ Only tangentially really, because already introduced by 15da8bb6fa19504624798965a4a221f029688e68.

**Comment by katrinleinweber** [comment]
PS: When I switch those two statement to `page.source == "md"` and swap the two links, I lock the `make serve`d page to always link to the `.Rmd` files, which then breaks the quick-links on https://swcarpentry.github.io/r-novice-inflammation/reference/ and the other, actually `md`-sourced pages.

**Comment by fmichonneau** [comment]
I think it comes from a recent modification in the expectation of the data that are included in the yaml headers of the episodes. The Rmd files should include: 

```yaml
source: Rmd
```
