### ISSUE TITLE
Can Jekyll ignore .Rproj.user/.../console.../... files?

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#358]
I'm sometimes noticing strange behaviour when running `make serve` https://github.com/swcarpentry/r-novice-inflammation/blob/4ce675e43799fd6b2f541630db35d1d4b48c175f/Makefile#L19-L21

from within RStudio( v1.1.447)'s Terminal tab (with Jekyll 3.7.2 on macOS 10.13.4). Every few seconds, RStudio seems to create a new temporary file (like `.Rproj.user/B7811A1D/console06/309F8013`) which triggers Jekyll to regenerate the site, which builds up to high CPU load.

Not sure how to reproduce it. That folder is ignored by Git: https://github.com/swcarpentry/r-novice-inflammation/blob/1411b0a7f3d803c91208da41a8a284cc4db75f0d/.gitignore#L30

Has anyone else observed this behaviour and/or can help debug this?

**Comment by fmichonneau** [comment]
you can try to add this folder to the "exclude" in `_config.yml` (https://jekyllrb.com/docs/configuration/#global-configuration)

```yaml
exclude:
  - .Rproj.user/
```
