### ISSUE TITLE
Make alt text for images less vague?

### ISSUE THREAD

**Issue by mesako** [swcarpentry/r-novice-inflammation#372]
The alt text for some lesson images does not specifically describe what is shown in the image. While this may not be as necessary for “supplemental” images that reinforce ideas already described in the text, some of the writing implies that the user must see/understand what the image conveys.

A good example of this pattern is found in the [Making R Packages section](http://swcarpentry.github.io/r-novice-inflammation/08-making-packages-R/) where the text reads: “Overall, your package directory should look something like this:” and the alt text for the corresponding image says, “R Package Structure.”

**Comment by katrinleinweber** [comment]
Hello Melissa :-) I see what you mean. I' happy to review a PR with your ideas to rephrase too vague alt texts.

**Comment by LoraArmstrong** [comment]
Hi there, I had a go at updating the alt text for the R package directory image, submitted in the PR above. I looked through the entire lesson and felt that this image was the only one that was not adequately described in the main text of the lesson, so this is the only alt text I updated.
