### ISSUE TITLE
Broken link to dataset: r-novice-inflammation-data.zip

### ISSUE THREAD

**Issue by cdarabos** [swcarpentry/r-novice-inflammation#377]
Link to dataset at the bottom of the page is broken: Download r-novice-inflammation-data.zip and move the file to this folder.
---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by katrinleinweber** [comment]
Great minds think alike, and sometimes at the same time even of different continents :-D

**Comment by diyadas** [comment]
Thanks for resolving the issue so quickly :)

and thanks again @cdarabos for bringing this to our attention!

**Comment by katrinleinweber** [comment]
It might have been something in #373. In 6c59c895b238ad927e0571b3cedaf0f17e3782c6, the whole metadata block was removed, but I tested that here as well, and it didn't help. I'll `git bisect` it and report back.

**Comment by katrinleinweber** [comment]
Meh, doesn't work that easily. When `bisect` checks out a commit that was introduced by #373, the working dir is purged of all the `r-novice` files, so `make serve` runs into lots of missing file errors, and doesn't even progress to building the `/setup` and I thus can't even check where the link breaks.

I'm now merging 7400b93450253fadbb0ee1263bb950fb4ca4f06a into each checked-out state during  bisecting.

cc @fmichonneau, @rgaiacs & @maxim-belkin: This might be interesting to you as well.

**Comment by katrinleinweber** [comment]
It seems that b2c0a4d4837ba582a9a46734904b376fea935906 triggered this bug, but probably in combination with [`setup.md`@c02276f1](https://github.com/swcarpentry/r-novice-inflammation/blame/c02276f17ef847299cf66932da6ec98defdc15d1/setup.md) not having been prepared for the v9.3.0 style update, as [`r-novice-gapminder`'s `setup.md`](https://github.com/swcarpentry/r-novice-gapminder/commit/2af2ca93c53e30364f11cb263b4334f6390b9565#diff-2cc0b07f42930e4520820be1fe66f913) was.

I'm not blaming anyone, maybe myself, but mostly the confusion during the first week of being a maintainer ;-)

**Comment by maxim-belkin** [comment]
Hmmm. The download link works for me

**Comment by katrinleinweber** [comment]
Before the two fixes https://github.com/swcarpentry/r-novice-inflammation/commit/c02276f17ef847299cf66932da6ec98defdc15d1 & https://github.com/swcarpentry/r-novice-inflammation/commit/18f6d4b578b8bac8b2ef764a9207a79fa68587da?

**Comment by maxim-belkin** [comment]
um, with them, actually 😬

**Comment by katrinleinweber** [comment]
Does it work at `git checkout c02276f17ef847299cf66932da6ec98defdc15d1`?
