### ISSUE TITLE
Suggestion: use typeof() to demonstrate that matrices are extensions of vectors and dataframes are extensions of lists

### ISSUE THREAD

**Issue by aabarug** [swcarpentry/r-novice-inflammation#379]
(This is part of my instructor checkout)

In the Data Types and Structures sections, the `class` and `typeof` functions are introduced. Under the matrix section, matrices are described as extensions of numeric and character vectors. Data-frames as described as special lists. It might be helpful to include `typeof()` and `class()` on a matrix and on a data-frame to illustrate that while the class might say matrix/data-frame, under the hood, they are indeed vectors and lists. It also clears up the difference between the two functions as in the notes, the one example where both `typeof` and `class` are used together on the same object (a character vector), the same result is returned (character).

**Comment by diyadas** [comment]
Thanks for your comment @aabarug ! While I agree with you, I'm a little concerned about time on this episode. On the other hand, it's a supplementary episode so I tend to think of it as an expansion in any case. @katrinleinweber what do you think?

**Comment by katrinleinweber** [comment]
Hi! Was preparing a workshop, sorry for the few days silence.

You mean under [13-supp-data-structures.Rmd#matrix](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/_episodes_rmd/13-supp-data-structures.Rmd#matrix), right? I haven't taught this part, so I think the best way to decide would be to review a pull request that changes the `.RmD` file in the way you mean.

I definitely agree with both your arguments that this would illustrate the example better, and would be an OK expansion.

**Comment by katrinleinweber** [comment]
PS @aabarug: Please include a "(fix #379)" in the message of the commit, if you make this change. It will unlock a little [GitHub magic](https://help.github.com/articles/closing-issues-using-keywords/) ;-)
