### ISSUE TITLE
Broken link in the lesson 

### ISSUE THREAD

**Issue by chsuong** [swcarpentry/r-novice-inflammation#385]
The link about the comma-separated values (CSV) format (http://swcarpentry.github.io/r-novice-inflammation/reference/#comma-separated-values-csv) is broken. The link is included in the first episode (http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/index.html).

**Comment by katrinleinweber** [comment]
Phew, thanks for the quick warning about this problem :-)

I'll have to test https://github.com/swcarpentry/r-novice-inflammation/blob/9c9198f5ce2f3f0ab073bd2276ded9aaa374ee55/Makefile#L84 still, but the site links should work again.

**Comment by chsuong** [comment]
The link in another episode also seems to be broken. The problematic link is https://swcarpentry.github.io/shell-novice/01-filedir/ on the page http://swcarpentry.github.io/r-novice-inflammation/03-loops-R/.

**Comment by katrinleinweber** [comment]
Thank you! Keep it up :-) Also with PRs, if you want to click on the `Improve this page` at the top whenever you find a broken link, and know the new/correct one.

**Comment by katrinleinweber** [comment]
Changing https://github.com/swcarpentry/r-novice-inflammation/blob/9c9198f5ce2f3f0ab073bd2276ded9aaa374ee55/Makefile#L84 does not seem to have effect, positive or negative on `make serve`, so I'll ignore it for now.
