### ISSUE TITLE
Reading and Writing CSV Files in R: Introduce na.strings argument and explain how to read CSV file by providing a filename only

### ISSUE THREAD

**Issue by mrakovic** [swcarpentry/r-novice-inflammation#387]
Hi everyone,
I would like to offer two suggestions related to the lesson "Reading and Writing CSV Files in R":
1. In most cases, researchers need to deal with missing data in their datasets, so introducing na.strings argument (among other read.csv arguments introduced in the lesson so far) may be a useful complement for those researchers who want to know, for example, how to convert empty cells in a dataframe to a NA string - conventional label that R understands as missing data point.
2. From my experience, some researchers prefer to place their CSV files into a working directory (root level, without using subfolders), so having this scenario covered in the read.csv introduction may be an addition worth considering. For example, read.csv(file = 'car-speeds.csv') will locate and read the file if it exists in a working directory (assuming that working directory was properly set before).
Looking forward to reading your comments.
Mladen

**Comment by katrinleinweber** [comment]
Hello :-) I agree with @diyadas' `2.` argument.

About `1.`: The  argument is also intended for cases in which the raw data contains something else, like `n.a.`, `--`, etc. It can also take a `c()`ombination of several strings. I think a PR changing exactly the phrases that you mean, or adding what you want to see included, would be best to decide. If you do, please include a "(fix #387)" in your commit message. It will unlock a little [GitHub magic](https://help.github.com/articles/closing-issues-using-keywords/) ;-)

**Comment by EastBayEv** [comment]
This is a great point! While the "Import Dataset" button is handy, I cannot find a way to pass a vector of na.strings into that field when using the "Import Dataset" button (only single values), thus making the hard-coding of `read.csv` even more valuable. 

Does anybody know if you can indeed pass a vector of na.strings into that field whilst using the "Import Dataset" button?

**Comment by PaulMelloy** [comment]
Hello, I have added a pull request to try and address this issue. #494 
I thought the addition would be best suited in the "Reading and Writing CSV Files" episode. I attempted to make it a challenge question after the `stringsAsFactors` argument topic.
Let me know if you think there are better data sets than the two I used as an example and I could edit it.
