### ISSUE TITLE
Potential reorganization of lesson (dataset info, GitHub + RStudio integration)

### ISSUE THREAD

**Issue by AmierohAbrahams** [swcarpentry/r-novice-inflammation#394]
Software Carpentry

With regards to the R-programming, before analysing the data and constructing graphs first provide a background  on the data that being investigated (Where the data was collected, How the data was collected and what we are trying to achieve by looking at the dataset). This keeps the learners interested and allows learners to formulate hypothesis which could be achieved by visualization through ggplot (Visualization with a purpose, hypothesis). 

Another thing to consider is to link GitHub to Rstudio directly after the terminal (Shell courses) are complete, so before doing the R-programming lectures. By doing this learners will be able to apply the shell commands by linking GitHub to Rstudio easily. Linking GitHub to Rstudio prior to the R-programming lectures allows for students to gain experience in committing,pushing and pulling on GitHub while the R-programming lectures are being taught. Thus providing learners with GitHub and Rstudio experience.

**Comment by katrinleinweber** [comment]
Dear @AmierohAbrahams,

a little bit of background on this example datasets is in [`index.md`](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/index.md). I'd be happy to review a PR that updates those few sentences to be more engaging. Let's continue that part of the discussion there then.

And let's discuss your RStudio suggestion in this issue. I agree basically and in the handful of workshops I participated, [`09-supp-intro-rstudio.Rmd`](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/_episodes_rmd/09-supp-intro-rstudio.Rmd) was usually pulled to the front of a workshop. Again, a PR that would formalise this would be welcome.

However, that opens up the whole discussion of whether we should imply to people that plain R console is less useful than RStudio. Currently, the philosophy of this lesson is to support both equally and thus the RStudio episodes is supplemental.

Kind regards,
Katrin

PS: I'll be on holiday for the rest of September, so I may not answer again this quickly to your reply or PRs ;-)

**Comment by katrinleinweber** [comment]
PPS: Since you mention linking Git & RStudio, I'd be happy to learn your thoughts on [FAIR-R/04-making-packages-R](https://github.com/TIBHannover/FAIR-R/blob/gh-pages/_episodes_rmd/04-making-packages-R.Rmd).

**Comment by katrinleinweber** [comment]
Due to several weeks of inactivity, I'm going to close this. @AmierohAbrahams: Please feel free to reopen, if still relevant.
