### ISSUE TITLE
indicating interest during Github registration

### ISSUE THREAD

**Issue by rmatumbas** [swcarpentry/r-novice-inflammation#405]
when creating a GitHub account you are requested to indicate your interest. GitHub should allow using space while typing your interest.  for example if I'm interested in **Statistics Analysis** I will have to combine the two using a hyphen/.dash. Is there a particular reason why space is not allowed?

**Comment by katrinleinweber** [comment]
Hi Romeo, this is the repository for the Carpentries' R lesson ;-) I'm guessing you signed up to GitHub during a workshop in which that lesson was taught.

Maybe they want to direct users to [existing topics](https://github.com/blog/2309-introducing-topics). Please consider [asking GitHub this question](https://github.com/support) if my guess is not the answer you sought.
