### ISSUE TITLE
Teaching '&' instead of '&&'.

### ISSUE THREAD

**Issue by reedacartwright** [swcarpentry/r-novice-inflammation#410]
In episode 4 we teach element-wise AND and OR comparisons.

> We can also combine tests. An ampersand, &, symbolizes “and”. A vertical bar, |, symbolizes “or”. & is only true if both parts are true:

However, for control flow `&&` and `||` are preferred:

> & and && indicate logical AND and | and || indicate logical OR. The shorter form performs elementwise comparisons in much the same way as arithmetic operators. The longer form evaluates left to right examining only the first element of each vector. Evaluation proceeds only until the result is determined. **The longer form is appropriate for programming control-flow and typically preferred in if clauses.** [Emphasis mine; from the `Logic {base}` help() page. ] 

Is this an oversight in the lesson, or is it intentional?

**Comment by katrinleinweber** [comment]
Dear @reedacartwright, thanks for the prompting question. I don't think there is any intention behind this, so I started a PR based on your suggestion. Please have a look: #412. Does it reflect what you & R prefer?
