### ISSUE TITLE
Unresolved question about default arguments?

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#413]
Please see: https://github.com/swcarpentry/r-novice-inflammation/blob/21a0ee0c7eaf71ccd4136b7691ade9aefaf739fe/_episodes_rmd/02-func-R.Rmd#L503-L535

Do you all feel that the "… functions always behave the same way?" question is resolved, by the `min` & `max` results below. Should there be some explanatory text?

**Comment by diyadas** [comment]
I think it good practice to make these sorts of things explicit, as it also offers an opportunity for learners to ask questions if they are confused about *why* these calls to the same function return different results. Thanks for catching this. I'd welcome someone to add explanatory text.

**Comment by katrinleinweber** [comment]
What do you think is the purpose of that `behave the same`-question? I followed the blame info back to https://github.com/swcarpentry/r-novice-inflammation/commit/08b1a9f0cac3bac4dc43f15cd6e08d7125d6f7bc, but am not sure where to check further ("r/novice")? Maybe @jdblischak or @gvwilson remember? If yes, please remove the "good first issue" label ;-)

I guess I understand why this challenge asks two learners to compare their solutions: to uncover mathematical errors in their formulae, no? But what is meant with "always behave"? If the two learners got the formula right, then `min()` & `max()` in the "Solution" will always equal `lower = ` & `upper = `. Is that the point of this challenge?

If yes, how about this rephrased question: "Do your two implementations produce the same results when both are given the same input vector and parameters?".

**Comment by diyadas** [comment]
Ah! I didn’t think that the discussion with the neighbor was about comparing implementations. I read the intent here as introducing the idea of arguments (and default arguments?) to functions.  

I see now that this is rather confusing. Perhaps we could remove the part about comparing with a neighbor and come up with a more explicit question. Or even a statement to this end.

**Comment by jdblischak** [comment]
> What do you think is the purpose of that behave the same-question? I followed the blame info back to 08b1a9f, but am not sure where to check further ("r/novice")? Maybe @jdblischak or @gvwilson remember? If yes, please remove the "good first issue" label ;-)

@katrinleinweber That question is from the original Python lesson developed by @gvwilson. The link below is to the first commit of python-novice-inflammation:

https://github.com/swcarpentry/python-novice-inflammation/blob/279cd853865b5e61469bb8c7c9009912fb773a9f/_episodes/06-func.md

> I guess I understand why this challenge asks two learners to compare their solutions: to uncover mathematical errors in their formulae, no?

That is also my understanding.

> But what is meant with "always behave"? If the two learners got the formula right, then min() & max() in the "Solution" will always equal lower = & upper = . Is that the point of this challenge?

I think the point is to get them thinking about testing. Try picking various input parameters and see the results. See if they can find edge cases where their functions give different results.

> If yes, how about this rephrased question: "Do your two implementations produce the same results when both are given the same input vector and parameters?".

I agree that makes it more explicit.

**Comment by katrinleinweber** [comment]
> I read the intent here as introducing the idea of arguments (and default arguments?) to functions.

That's another aspect that I think confused me initially. Both that concept and the math are being requested a the same time. And the question didn't seem to fit either.

> [...] thinking about testing. Try picking various input parameters [...] find edge cases

I wonder how often and/or in which way this happened in a workshop?

> I agree that makes it more explicit.

Cool, thanks for confirming :-) I would consider removing the `min()` & `max()` checks then, and the `answer <- ` assignment, because the function outputs would already allow visual confirmation.

**Comment by katrinleinweber** [comment]
> [...] visual confirmation

Which could be superceded by introducing `testthat::expect_equal()` right then and there ;-)
[I'm working on a draft about this](https://github.com/TIBHannover/FAIR-R/pull/19/files#diff-57331ba5e4f65f235644061cc45d43aa).

**Comment by jdblischak** [comment]
>  I would consider removing the min() & max() checks then, and the answer <- assignment, because the function outputs would already allow visual confirmation.

Those lines are never shown to the learner (the chunk has `include = FALSE` set). They are only visible if you read the source code. I put them there for any instructors/helpers reading through the lesson material. When an instructor goes to review the exercise live, these are suggested lines that they could run.

You are welcome to remove them if you don't like them, but I think using `min()` and `max()` is more convenient compared to printing out the entire rescaled column:

```
> answer <- rescale(dat[, 4], lower = 2, upper = 5)
> min(answer)
[1] 2
> max(answer)
[1] 5
> rescale(dat[, 4], lower = 2, upper = 5)
 [1] 5 3 5 2 5 4 4 4 5 4 2 2 3 2 3 2 2 3 3 2 5 5 5 3 3 3 4 3 4 3 2 5 4 3 4 5 4 4 5
[40] 5 4 5 5 5 5 4 5 5 5 4 3 4 4 3 3 5 4 3 3 2
```

This is the same approach used in earlier in the lesson to evaluate the results of the function `center`.

https://swcarpentry.github.io/r-novice-inflammation/02-func-R/index.html#testing-and-documenting

**Comment by katrinleinweber** [comment]
> include=`FALSE`

True, but if they are intended for the instructor to present, then the disconnect between the question and the solution is still there from the learners' PoV ;-) Let's go for rephrasing the question.
