### ISSUE TITLE
Data Types and Structures: discussion on types versus structures

### ISSUE THREAD

**Issue by captainalan** [swcarpentry/r-novice-inflammation#423]
I think it would be helpful to include a discussion on data **types** versus **structures** in the [Data Types and Structures](https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/) lesson.

Particularly for users of R that have some experience with other programming languages (e.g. Python, ...), one of the most difficult parts of getting started with R is understanding what sorts of objects there are in R and how these objects behave. As the lesson points out, "**Everything** in R is an object". However, unlike in other programming languages, users typically interact with primitive data types only through the (complex) data structures of atomic vector, list, etc. 

This contrasts with how many students typically first encounter the idea of "data types". In C++/C#/Java/etc. students might  first learn `int i = 0;`. We don't typically discuss `i` as a "data structure" and to do something like add `i` to an array would not work. However, in R you can do things like `c(1:10) + 1`

I would be happy to work on this issue, in particular by adding some information from the [Data Strcutures chapter](http://adv-r.had.co.nz/Data-structures.html) of Hadley Wickham's *Advanced R*.

**Note**: I stumbled across this repository/project through a Google search for ["r data types vs structures"](http://google.com/search?q=r+data+types+vs+structures). It is the first result for this search query as of 5/4/2019!

**Comment by katrinleinweber** [comment]
Thanks for pointing this out, Alan! Do you think that any of the ["objectives" or "keypoints" should be clarified or corrected](https://github.com/swcarpentry/r-novice-inflammation/edit/master/_episodes_rmd/13-supp-data-structures.Rmd)? If yes, we can discuss specifics in a (draft) PR. Adding the book reference you suggest could also work nicely (to the start or end of that episode, maybe?).

Before working on anything larger than that, however, please note that [this lesson is "for non-programmers"](https://github.com/swcarpentry/r-novice-inflammation#r-novice-inflammation) and that ["more concepts and tools"](https://github.com/swcarpentry/r-novice-inflammation/blob/master/CONTRIBUTING.md#what-to-contribute) are outside of its scope.

*Re: Note* Some SEO just does itself :-D

**Comment by captainalan** [comment]
Here are some suggestions I believe could easily be incorporated without introducing more concepts and tools.

## Addition to first objective

- Expose learners to the different data types in R *and show how these data types are used in data structures*.

## Addition to second key point

- R's basic data structures include [...]. Some of these structures require that all members be of the same datatype (e.g. vectors) while others permit multiple datatypes (e.g. lists).

This information is presented implicitly in the lesson, which describes how to work with some data structures and restrictions that go into making them. Clarifying these points in the objectives/key points will be reinforcing what is already there. 

## Other things

I could also look over doing some edits to some wording in the text, e.g.   

Make objectives consistently start with verbs:

> ~~Getting familiar~~ -> *Get familiar* with the different...

the second paragraph in "Understanding Basic Data Types in R":

> *Data structures are* very important to understand because these are the objects you will manipulate...

**Comment by katrinleinweber** [comment]
As a pull request, please ;-) If you open https://github.com/swcarpentry/r-novice-inflammation/edit/master/_episodes_rmd/13-supp-data-structures.Rmd, is there `Propose file change` at the bottom? If yes, please make the edits.

**Comment by taddallas** [comment]
PR merged, I believe this may be complete and can be closed?

**Comment by HaoZeke** [comment]
Yup, good call, thanks @taddallas, @captainalan and @katrinleinweber!
