### ISSUE TITLE
Missing challenge/exercise solutions and incorrect boxes

### ISSUE THREAD

**Issue by diyadas** [swcarpentry/r-novice-inflammation#424]
Issue to keep track of missing solutions and incorrect boxes, in preparation for June 2019 lesson release. This tracks only supplementary episodes at the moment.

So far, incorrectly formatted challenges:
- [x] Solution given, but not formatted with hide button: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/10-supp-addressing-data.Rmd#L68
- [x] No solution given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/10-supp-addressing-data.Rmd#L79
- [x] No solution given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/10-supp-addressing-data.Rmd#L94
- [x] No solution given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/10-supp-addressing-data.Rmd#L107
- [x] No solution given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/10-supp-addressing-data.Rmd#L176
- [x] No solution given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/10-supp-addressing-data.Rmd#L192
- [x] No solution given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/12-supp-factors.Rmd#L170 (please put a period on the end of L170 when fixing)
- [x] No solution given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/12-supp-factors.Rmd#L197
- [x] No solution given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/13-supp-data-structures.Rmd#L156
- [x] Not formatted as a challenge: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/13-supp-data-structures.Rmd#L356
- [x] Not formatted as a challenge: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/13-supp-data-structures.Rmd#L368
- [x] Solution given, but not formatted with hide button: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/13-supp-data-structures.Rmd#L458
- [ ] No solution given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/14-supp-call-stack.Rmd#L131

Incorrect data directory:
- [x] https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/11-supp-read-write-csv.Rmd#L39 (ep 1 directs them to `setwd("~/Desktop/r-novice-inflammation/")` and data will be in `data` subdirectory.)

Typos / formatting, while we're at it:
- [x] https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/11-supp-read-write-csv.Rmd#L53 : " - see" instead of " -see"
- [x] https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/12-supp-factors.Rmd#L82: smart quotes have rendered confusingly
- [x] https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/12-supp-factors.Rmd#L139: need spaces around =

**Comment by diyadas** [comment]
@katrinleinweber Can you figure out what the aim is of  https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/13-supp-data-structures.Rmd#L156 ?

The best guess I have is that they're 1 dimensional, and that is the definition of a vector. Is that the desired outcome? (Should we remove/rephrase this question?)

**Comment by katrinleinweber** [comment]
I guess so. Because several more 1D vectors follow below that challenge, we could maybe move it to directly above the `Matrix` section.

**Comment by diyadas** [comment]
I pushed the others, but I could use some help with the call stack diagram.

**Comment by katrinleinweber** [comment]
About what specifically? I guess we could try to draw our solution idea seperately (e.g. in Google Slides) and compare.

**Comment by katrinleinweber** [comment]
Duplicating an existing SVG and changing the labels in the source code works OK as well (4f5e8aa). However, I'm not sure whether any of https://github.com/swcarpentry/r-novice-inflammation/commit/90e50b65268225270c09411262a6ddc74c2f8156?short_path=5ab0efb#diff-ec99aa78325c779963845ff010274632 is similar enough to what we need here.

Which also makes me wonder why it was OK for the [previous release](https://zenodo.org/record/838772) to not include a solution to that exercise? I don't think we need to be perfect / address every single issue either.

**Comment by diyadas** [comment]
I'm closing this one for now -- we can revisit the diagram if it comes up. Thanks!

**Comment by katrinleinweber** [comment]
You're welcome :-)
