### ISSUE TITLE
Missing challenge solutions in main episodes

### ISSUE THREAD

**Issue by diyadas** [swcarpentry/r-novice-inflammation#427]
Main episode challenges requiring solutions:
1. - [x] optional, but some text would be good. https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/01-starting-with-data.Rmd#L94
2. - [x] optional, but some text would be good. https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/01-starting-with-data.Rmd#L101
3. - [x] needs a diagram for solution: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/01-starting-with-data.Rmd#L230
4. - [x] needs a solution: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/01-starting-with-data.Rmd#L451
5. - [x] needs a solution: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/01-starting-with-data.Rmd#L561

6. - [x] needs a solution: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/02-func-R.Rmd#L207
7. - [x] missing solution to attempt to do multiplication, should revise so the challenge is clear to be addition or subtraction with TWO numbers _only_ : https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/05-cmdline.Rmd#L209
8. - [x] solution for shorter command-line arguments not given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/05-cmdline.Rmd#L320
9. - [x] solution does not report total number of lines when multiple files are given: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/05-cmdline.Rmd#L384
10. - [x] 1&2 don't need a solution, but 3 should have one: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/06-best-practices-R.Rmd#L156
11. - [x] 1 needs a solution, unclear that writing solution for 2 would be useful: https://github.com/swcarpentry/r-novice-inflammation/blob/master/_episodes_rmd/08-making-packages-R.Rmd#L177

**Comment by katrinleinweber** [comment]
4. is beyond me, and I don't find any hints via the blame views, nor through https://carpentries.topicbox.com/search:eon%20slice, nor in [python-novice-inflammation](https://github.com/swcarpentry/python-novice-inflammation/search?q=eon&unscoped_q=eon).

Currently I suggest to remove it: 072126e, but I'm also find with keeping it without a solution.

**Comment by katrinleinweber** [comment]
Closed by f5c65fe653b52f995504103c0803c6ae53e485aa & 8fe49a959b17a161b1f67e48ccd56499fd803dd3.
