### ISSUE TITLE
CSV file photos are screen shots of Excel files instead of CSV files

### ISSUE THREAD

**Issue by sasutils** [swcarpentry/r-novice-inflammation#434]
Seems like a great learning tool, but I am curious why do the photos of supposed CSV file outputs have photos of EXCEL spreadsheets instead of the actual CSV files?  CSV files are just plain text files.   Showing them as if they were EXCEL files will confuse novice programmers into thinking that they are spreadsheets. Plus if you open a CSV file in EXCEL then there is extremely large probability that EXCEL will not properly display the content.

**Comment by katrinleinweber** [comment]
Hello @sasutils & thanks for making these points :-)

I'm not sure why [the `csv...png` files in the `fig` folder](https://github.com/swcarpentry/r-novice-inflammation/tree/master/fig) are the way they are. I followed the [`git blame` trail a few steps into the past](https://github.com/swcarpentry/r-novice-inflammation/commit/f44bfdf25633e8411ba9cd3155a737071e28a725), but found no good explanation. Maybe @jeremycg remembers?

Please feel free to send a PR with better screenshots. Maybe in one of the [Carpentries-suggested editors](https://carpentries.github.io/workshop-template/#editor) or even as a textbox-represenation of the shown [`.csv` files](https://github.com/swcarpentry/r-novice-inflammation/tree/master/_episodes_rmd/data).

Thank you!
