### ISSUE TITLE
Labels of code chunks (bash/R/output) in lesson 5, command line

### ISSUE THREAD

**Issue by timotheenivalis** [swcarpentry/r-novice-inflammation#436]
Hi everyone, 

I got a bit confused by the labels of code/output chunks in 
[lesson 5 http://swcarpentry.github.io/r-novice-inflammation/05-cmdline/index.html ](http://swcarpentry.github.io/r-novice-inflammation/05-cmdline/index.html).

For instance the first one is labelled "R" but is bash code; while the 4th one is labelled "output" while it is R code without any output (although not meant to be run in R directly).
I haven't counted exactly, but maybe about a fifth of the chunks seems mislabelled. 

If the problem is real (I may just be super confused!) I am happy to try and submit a pull request correcting it.

I would label as "Bash" (using `{: .language-bash}` ) anything that is meant to be written and run in the command line, label as "R" (using `{: .language-R}`) anything that is meant to be written and run in R, and label "Output" anything that is returned by R or Bash. I am not 100% sure what to do with chunks that show R-code not meant to be run directly, but instead to be saved and called in bash with Rscript later. The "R" label seems more logical to me, but maybe they were meant to look different from chunks to be run directly in R, hence the use of "Output" for them? (If so, it may be good to create a new label type for those?)

Cheers,

Timothee

**Comment by fmichonneau** [comment]
Hi Timothee, you're not super confused, it's definitely a bug. I have a fix on the way in the styles repository.

**Comment by fmichonneau** [comment]
:wave: @swcarpentry/r-novice-gapminder-es-maintainers , @swcarpentry/r-novice-gapminder-maintainers, @swcarpentry/r-novice-inflammation-maintainers I fixed this issue in the styles repository, you may want to consider upgrading to the latest version of the template to have this fix in your respective repositories. I'm re-opening the issue as it still exists in this repository until a newer version of the template is included in the repo.

**Comment by katrinleinweber** [comment]
To [`styles/master:6d015fe`](https://github.com/carpentries/styles/commits/6d015fe8f75ad7435a22aa8491dcfc66eed3ebb6), instead of any tag, correct? Would cherry-picking 6d015fe also be OK?

**Comment by fmichonneau** [comment]
I _think_ that if you only cherry pick 6d015fe it will make a future upgrade more difficult. It's probably best to pull all commits up to 6d015fe.
