### ISSUE TITLE
List this lesson on CRAN.R-project.org/other-docs.html

### ISSUE THREAD

**Issue by katrinleinweber** [swcarpentry/r-novice-inflammation#447]
https://cran.r-project.org/other-docs.html

- [ ] find out [how to contribute there](https://www.r-project.org/bugs.html)
- [ ] decide: list Zenodo release or GitHub page?
- [ ] send patch/email/etc.

**Comment by boshek** [comment]
I am looking for a contribution to complete my carpentry instructor training. I'd like to offer to take this on if that seems suitable.

**Comment by HaoZeke** [comment]
Sure, @boshek thanks a lot! When you've gotten it listed perhaps you could open a PR for adding the link to the readme as well? Something like "Listed on CRAN". This way it'd be easier to track your contribution on this repository.

**Comment by boshek** [comment]
Sounds good but just a clarification - you want me to add a link to here: https://cran.r-project.org/other-docs.html on the README for this repo? Wouldn't that create a sort feedback loop as the link in the README would take to you to a place which links back to repo?

**Comment by HaoZeke** [comment]
That's true, but the idea is to point out that this lesson is listed on cran. Actually it's a bit artificial, so it's OK either way.

**Comment by HaoZeke** [comment]
Oops. Good catch! I'll close this now, thanks :)
Looking forward to working with you on another issue for the checkout process @boshek!

**Comment by boshek** [comment]
@HaoZeke I'd re-open actually. I volunteered the maintain the list so if that offer is accepted it make again become a living entity.
