### ISSUE TITLE
Link to Setup files in each Episode

### ISSUE THREAD

**Issue by MichaelBAnderson** [swcarpentry/r-novice-inflammation#448]
Dear Software Carpentry Community,

My name is Michael Anderson and I am posting this issue as part of the Instructor Checkout process.

While I have was reviewing the different lessons/episodes in preparation for the demonstration portion of the Checkout process, it took me a while to realize the required files were on the Schedule page for each lesson, via the Setup link.  While following a lesson for the first time, it would have been convenient for me to have the Setup link (of data files) at the top of each Episode page.  Would this be more trouble than it is worth to accomplish? 

I am not sure if this would also help others but it would have helped me in the beginning so I thought it may be worth suggesting for new users.

Thanks in advance.  I look forwarding to being a part of this community.

-Michael Anderson

**Comment by diyadas** [comment]
Hi Michael, welcome!

I understand that the location of the link to the setup page is difficult to find and I agree that it's confusing to have it in the schedule. I'd prefer to have it linked just once, but placed more prominently on the lesson homepage. However, the location of that link is actually determined by the lesson template, which applies to all lessons. 

@rgaiacs any chance you could [transfer this issue](https://help.github.com/en/articles/transferring-an-issue-to-another-repository) to carpentries/styles or carpentries/lesson-template? I'm not sure which one is more appropriate and I don't have write permissions on either, in any case.

(Michael, this counts as an interaction for the purposes of the checkout process, and you can proceed with the rest of the steps. Good luck!)

**Comment by rgaiacs** [comment]
@fmichonneau Can you do the transfer that @diyadas requested? I don't have the permission.

**Comment by MichaelBAnderson** [comment]
Thanks Diyadas!

**Comment by fmichonneau** [comment]
unfortunately, the transfer issue feature doesn't work across GitHub organizations. I opened the issue manually here: https://github.com/carpentries/styles/issues/434 Thanks for the report @MichaelBAnderson
