### ISSUE TITLE
Setting directories with tab auto-complete

### ISSUE THREAD

**Issue by michaelofrancis** [swcarpentry/r-novice-inflammation#452]
Hi all,

In the first lesson ("Analyzing Patient Data"), when an absolute beginner is setting their working directory to load in csv files, it may be useful to let them know that they can use the tab key within the setwd("") quotes to see a list of possible directories. I imagine that getting some folks to type in their working directory correctly may be difficult in a live session and this could make it easier.

**Comment by diyadas** [comment]
Thanks for the suggestion. I do have some concern about growing the size of this episode. Perhaps it’s possible to reference the Unix shell on tab completion (as it’s frequently taught before this lesson) and this keep the reference short?

Thoughts @katrinleinweber ?

**Comment by katrinleinweber** [comment]
When I +1'ed the above, I assumed that we're talking only about 2 or 3 sentences, maybe scattered throughout 1 or 2 episodes to nudge learners towards the `tab`. A reference to https://swcarpentry.github.io/shell-novice/02-filedir/index.html#nelles-pipeline-organizing-files is a good idea in any case :-)

**Comment by diyadas** [comment]
Cool! If anybody wants to submit a PR, happy to review.
