### ISSUE TITLE
Code typo in "Testing and Documenting" section of (2) Creating Functions

### ISSUE THREAD

**Issue by michaelofrancis** [swcarpentry/r-novice-inflammation#453]
The function "center" in the Testing and Documenting section is written like this
```
center<- function(data, midpoint){
    new_data<- (data-mean(data)) + midpoint
}
```
The user is then asked to code the following:
```
z<-c(0,0,0,0)
center(z,3)
```
There are two problems here. First, the output isn't including in the text, like it has been throughout the tutorial so far. But second, there is no output for this function, because neither a return() nor a variable is including in the conclusion of the function. Since returns are being explicitly included in functions before and after this center function, I would recommend rewriting the function like this:
```
center<- function(data, midpoint){
    new_data<- (data-mean(data)) + midpoint
    return(new_data)
}
```

Here is a screenshot of the section I'm talking about for reference:
![image](https://user-images.githubusercontent.com/51752343/67112017-440acd80-f1a4-11e9-9b51-f015147231ea.png)

**Comment by katrinleinweber** [comment]
My bad, sorry! Thanks for pointing this out :-)
