### ISSUE TITLE
Two small typos

### ISSUE THREAD

**Issue by michaelofrancis** [swcarpentry/r-novice-inflammation#454]
Hi, I found two typos in the Data types and Structures section of Programming with R

![image](https://user-images.githubusercontent.com/51752343/67213776-9dfdd400-f3ec-11e9-81bc-668e8b9bd27f.png)

![image](https://user-images.githubusercontent.com/51752343/67214081-21b7c080-f3ed-11e9-9627-2f479baa68a4.png)

**Comment by diyadas** [comment]
Thanks for catching these! If you or anyone else would like to file a PR to correct these, we’ll be happy to merge.

**Comment by katrinleinweber** [comment]
@michaelofrancis: if you want to try, use the "Improve this page" link on top of each episode page ;-)
