### ISSUE TITLE
File commadec.txt missing from r-novice-inflammation-data.zip

### ISSUE THREAD

**Issue by LUS24** [swcarpentry/r-novice-inflammation#463]
Hi, I couldn't find the file **commadec.txt** in the zipped folder so I [created an alternative](https://drive.google.com/file/d/1uaWa-lbKsRLwqHW7DsctLCmAxwqAir7l/view) derived from the file **sample.csv** where I replaced all "," with ";" and then all decimal points with ",".

Hope it helps
Cheers
Leo

**Comment by zacharyrmiller** [comment]
Thanks for creating this alternative file! It seems that it was never added to the zip file, however. I have submitted a [pull request ](https://github.com/swcarpentry/r-novice-inflammation/pull/480)updating the zip to include the missing file.

**Comment by HaoZeke** [comment]
Closing thanks to the PR from @zacharyrmiller ^_^
