### ISSUE TITLE
Episode 1: "Printing with Parentheses"

### ISSUE THREAD

**Issue by kekoziar** [swcarpentry/r-novice-inflammation#466]
If we're modeling proper data management and reproducible science, the example in "Printing with Parentheses"  `(total_weight <- weight_kg + weight_lb)` should have one of the variables changed so the units are the same.  perhaps `(total_weight <- weight_kg*2.2 + weight_lb)`

**Comment by HaoZeke** [comment]
Excellent point. Thanks! Would you be willing to open a PR resolving this?

**Comment by kekoziar** [comment]
Yes, @HaoZeke.  Thanks!

**Comment by EastBayEv** [comment]
Awesome trick!

**Comment by HaoZeke** [comment]
I'll be closing this now, thanks again!!
