### ISSUE TITLE
Fluid Representations in Addressing Data

### ISSUE THREAD

**Issue by eigensong** [swcarpentry/r-novice-inflammation#474]
Dear Carpentries Community,

In my instructor training I learnt about "fluid representations" where multiple words for the same concept can confuse learners. I noticed that in the [Addressing Data](http://swcarpentry.github.io/r-novice-inflammation/10-supp-addressing-data/index.html) most of the lesson is really careful to avoid fluid representations, by consistently using the word addressing to describe accessing parts of a data frame, rather than mixing in words like subsetting or indexing. However, the titles for the three sections of the types of addressing are:
Addressing by Index
Addressing by Name
Logical Indexing

While I agree that "logical indexing" is the standard way to call this, and that students should be made aware of it, I think it might be clearer to change the title to "Addressing by Logical Vector" (or something similar) and then mention in that section that this is often referred to as "logical indexing." 

Any thoughts?

Cheers,

Elena

**Comment by HaoZeke** [comment]
Hi Elena,

That's a really great point regarding the text consistency. I think as long as we drop the term Logical Indexing in the main text we should be good to go with replacing the heading. Would you be willing to open a pull request with this change?

Thanks a ton,
Rohit

**Comment by eigensong** [comment]
Hi Rohit,

Thanks for your feedback. I'm happy to try open a pull request with this change, but I'm still learning how to use git, so it might take me a little while to work my way through the instructions.

Cheers,

Elena

**Comment by HaoZeke** [comment]
Hi Elena,

Thanks for the follow up! Please take all the time you need, and thanks again.

---
Rohit

**Comment by eigensong** [comment]
Hi Rohit,

I've opened this pull request https://github.com/eigensong/r-novice-inflammation/pull/1 . Should I have somehow linked it to this open issue?

Cheers,

Elena

**Comment by HaoZeke** [comment]
Hi Elena,
Thanks for the PR! It links back to this issue so I can assign it to be closed once we merge the PR in :)
---
Rohit

**Comment by eigensong** [comment]
Hi Rohit,

I tried another pull request. It's linked above. Let me know if I need to do anything else.

Cheers,

Elena

**Comment by HaoZeke** [comment]
Thanks @eigensong!
