### ISSUE TITLE
Missing File in 'Programming with R: Analyzing Patient Data'

### ISSUE THREAD

**Issue by mam737** [swcarpentry/r-novice-inflammation#479]
While looking at the Programming with R: Analyzing Patient Data module [here](http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/index.html), I noticed that the 'Reading Different Decimal Point Formats' uses the file 'commadec.txt'. However, this file is missing from the data folder housed in r-novice-inflammation-data.zip. I downloaded the zip file from this [page](http://swcarpentry.github.io/r-novice-inflammation/setup.html), for reference. I'm not sure where this file is. 

Best,
Manisha

**Comment by zacharyrmiller** [comment]
This issue was noted earlier (#463 [here](https://github.com/swcarpentry/r-novice-inflammation/issues/463)), but apparently never resolved. I have submitted a [pull request](https://github.com/swcarpentry/r-novice-inflammation/pull/480) updating the .zip to include the missing file.

**Comment by HaoZeke** [comment]
Closed thanks to https://github.com/swcarpentry/r-novice-inflammation/pull/480 by @zacharyrmiller. Thanks for noticing this @mam737.
