### ISSUE TITLE
Fix platform-specific setup instructions

### ISSUE THREAD

**Issue by ndporter** [swcarpentry/r-novice-inflammation#484]
The [setup instructions](http://swcarpentry.github.io/r-novice-inflammation/setup.html) include the following line:
> If it’s not unzipped yet, double-click on it to unzip it. You should end up with a new folder called `data`.

Double-click to unzip is default behavior on Mac but not Windows ([official Windows directions](https://support.microsoft.com/en-ae/help/4028088/windows-zip-and-unzip-files)). I assume there's some variability on Linux. Directions should not be platform-specific for lessons designed for multiple platforms.

For consistency with the abbreviated nature of the remainder of the instructions, I suggest changing to:
>If it’s not unzipped yet, unzip it. There should now be a folder called `data` in the `r-novice-inflammation` folder.

If the remainder of the instructions were more detailed, it might make sense to link to platform-specific instructions for true beginners there (that may not know how to unzip) but in that case, all three platforms would need to be represented.

**Comment by HaoZeke** [comment]
Excellent catch! Could you open a PR with the minimal instruction set? I'm reasonably certain handling three platforms for unzipping in this lesson is a bit overkill. Thanks and sorry for my late response
