### ISSUE TITLE
Multi lines commenting

### ISSUE THREAD

**Issue by Ammar-K** [swcarpentry/r-novice-inflammation#485]
Hi, 
In "Introduction to RStudio" <r-novice-inflammation/_episodes_rmd/09-supp-intro-rstudio.Rmd>
it might be helpful to add the shortcut for multiple lines comment/uncomment (Ctrl+Shift+c) under "#Commenting" section, I find it very helpful and wished I know it before.

**Comment by HaoZeke** [comment]
Sounds great, would you like to submit a PR for the same?

**Comment by Ammar-K** [comment]
Done 👍

**Comment by Bisaloo** [comment]
Hi @Ammar-K, thanks for your suggestion! I notice you opened the pull request [in your own fork of this repository](https://github.com/Ammar-K/r-novice-inflammation/pull/1). Instead, it should be in this repository: https://github.com/swcarpentry/r-novice-inflammation.

Would you like to try opening a PR with your changes here? If you're available to do this at this time, I can copy the changes here myself and [credit you as commit co-author](https://github.blog/2018-01-29-commit-together-with-co-authors/).

Thanks!
