### ISSUE TITLE
setwd in beginning of lesson is bad practice

### ISSUE THREAD

**Issue by Alanocallaghan** [swcarpentry/r-novice-inflammation#512]
Running setwd in the beginning of an R session is horrible practice, but it's currently part of the [first lesson](http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/index.html).

This should be changed, if for no other reason than for fear of having [Jenny Bryan come and set learners' computers on fire](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/).

Also this is detailed as bad practice [later](http://swcarpentry.github.io/r-novice-inflammation/06-best-practices-R/index.html).

I can see two ways of doing this:

1. include an RProject in the zip download
2. tell users to start by making a project.

I would favour the latter personally.

Actually reading through the lesson - episode 6 says "don't setwd" but episode 11 is back at it again.

If I'm being pedantic (apparently I am) I would also say:
- "nested functions" [here](http://swcarpentry.github.io/r-novice-inflammation/02-func-R/index.html) are nested calls not nested functions.
- `stopifnot(action %in% c("--min", "--mean", "--max"))` should probably be  
  `match.arg(action, choices = c("--min", "--mean", "--max"))` [here](http://swcarpentry.github.io/r-novice-inflammation/05-cmdline/index.html),
  or at least `match.arg` should be mentioned as an alternative.

I'm happy to make a PR to change these if maintainers think they're not awful ideas

**Comment by HaoZeke** [comment]
I think these are all great! Would love to see a PR with these. Thanks :)
