### ISSUE TITLE
Exercise timing missing for analyzing patient data

### ISSUE THREAD

**Issue by worcjamessmith** [swcarpentry/r-novice-inflammation#519]
The first episode in the programming with R lesson (http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/index.html) states that the time for exercises is 0 minutes. However, there are several exercises that I expect would take about 10-15 minutes to complete. Should the exercise timing be updated?

**Comment by HaoZeke** [comment]
Sure, that's a great catch, thanks for bringing it up! Would you be willing to open a PR for the same?

**Comment by worcjamessmith** [comment]
Yes, do those timings seem reasonable to you? I.e. 10-15 mins. I haven't actually taught this episode so unsure how long it takes in real life.

**Comment by HaoZeke** [comment]
Yup, I've personally never spent longer than ten minutes but 10-15 sounds perfect. :)

**Comment by worcjamessmith** [comment]
I went to open a PR and noticed that exercise time is also missing from other episodes e.g. http://swcarpentry.github.io/r-novice-inflammation/02-func-R/index.html. It might be worth someone going through all the lessons to check, but I didn't yet have time. 

Also, changing these will require updating the home page (http://swcarpentry.github.io/r-novice-inflammation/) to update the timings, but I wasn't able to work out how to do this or whether it is done automatically.

**Comment by ubdbra001** [comment]
I noticed the same thing, It looks like every episode in the lesson has 0 mins for exercises.
Happy to open a pull request for all, just want to check the timings seem sensible:
1. _Analyzing patient data:_ 10-15 mins as @worcjamessmith suggests
2. _Creating functions:_ 10 mins
3. _Analyzing multiple data sets:_ 10 mins
4. _Making choices:_ 10-15 mins
5. _Command-line programs:_ 5 mins
6. _Best Practices for Writing R Code:_ 5 mins
7. _Dynamic Reports with knitr:_ 5 mins
8. _Making Packages in R:_ 3 mins
9. _Introduction to RStudio:_ 0 mins
10. _Addressing Data:_ 7 mins
11. _Reading and Writing CSV Files:_ 5 mins
12. _Understanding Factors:_ 5 mins
13. _Data Types and Structures:_ 7-10 mins
14. _The Call Stack:_ 2-3 mins
15. _Loops in R:_ 0 mins

I'd also echo the question about whether the timings on the main page are updated manulally or automatically for this.

**Comment by HaoZeke** [comment]
Hi @ubdbra001. Thanks for going over these, the timings look great. I can't recall at the moment if they are updated or not, we can deal with that in a separate PR. Please go ahead with the timings from lesson 2 onwards. @worcjamessmith It would be good to have a PR relating to the first lesson :)

**Comment by ubdbra001** [comment]
Great will do!

**Comment by Bisaloo** [comment]
Hi @worcjamessmith & @ubdbra001, thanks again for catching this and offering to fix it.

Are you still interested and available to submit pull requests for this?

We're always happy to let people contribute directly but if it doesn't work for you, I can integrate the changes myself and mark you as [co-authors of the changes](https://github.blog/2018-01-29-commit-together-with-co-authors/).
