### ISSUE TITLE
Suggestion for making an R project when starting with the lecture material

### ISSUE THREAD

**Issue by iochatz** [swcarpentry/r-novice-inflammation#535]
In the set up instructions (http://swcarpentry.github.io/r-novice-inflammation/setup.html), it is mentioned that the participants should download the zip file and create a folder in their desktop to store it. Then at the beginning of the course material (http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/index.htmlhttp://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/index.html), there is a suggestion to create a new project by creating a new folder. 

This might be a bit confusing for novice users and could result in two folders with the same name (and one of them lacking the data). I would suggest to make a new project by choosing an existing folder (the one created during the set up and already containing the downloaded files) instead of creating a new folder.

**Comment by HaoZeke** [comment]
Thanks @iochatz, that sounds like a good suggestion, would you be willing to open a PR for the same?

**Comment by nkandhari** [comment]
This issue has been resolved and the steps have been added in the index.html page (http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data/index.html)
It's safe to close this issue.

**Comment by HaoZeke** [comment]
Thanks for the heads up @nkandhari :)
