### ISSUE TITLE
Alt Text for graph 

### ISSUE THREAD

**Issue by brynnelliott** [swcarpentry/r-novice-inflammation#568]
We have been working to add alt text to all of our lessons. 

Line 321 - creates 6 different charts. All have alt text "plot chunk of loop analyze" - all of the charts show something a little different - it would be helpful to be able to show different alt text for each graph - or come up with alt text that could fit all 6 charts 

```{r loop-analyze, fig=FALSE}
filenames <- list.files(path = "data",  
                        # Now follows a regular expression that matches:
                        pattern = "inflammation-[0-9]{2}.csv",
                        #          |            |        the standard file extension of comma-separated values
                        #          |            the variable parts (two digits, each between 0 and 9)
                        #          the static part of the filenames
                        full.names = TRUE)
filenames <- filenames[1:3]
for (f in filenames) {
  print(f)
  analyze(f)
}
```

**Comment by Bisaloo** [comment]
Thanks for the heads up! This was fixed in https://github.com/swcarpentry/r-novice-inflammation/commit/2ddc0afe81a7ede5790a61fd9c569aac69151e62.
