### ISSUE TITLE
Some parts needed to as.numeric before running function

### ISSUE THREAD

**Issue by chendaniely** [swcarpentry/r-novice-inflammation#58]
@mlammens taught at NYAS this week, and some parts needed an `as.numeric` cast.

This is a place holder to see what was different from the lesson in the repo and the lesson taught.

**Comment by mlammens** [comment]
@chendaniely This problem occurred while going through the "Creating Functions" lesson. I deviated from the lesson by trying to apply the `center` function on a row of the `dat` data.frame as opposed to a column. This apparently violates recent conventions set for dealing with rows in data.frames. Though using `apply` with data.frames, where `MARGINS = 1` does not seem to have the same problems.

**Comment by jdblischak** [comment]
Yes, this is an unfortunate aspect of the current lesson. The operations need to be done on columns, unless applying to all the rows with `apply`. One option to fix this would be to convert the data to a `matrix`, but that proposal was voted down in favor of keeping the data in the familiar `data.frame` object that novices are likely to encounter (see [PR][]).

We've already had a similar [discussion][]. It would be nice to have this point documented in the [discussion page][discuss] of this repo. Would one of you be able to send a PR?

[discussion]: https://github.com/swcarpentry/bc/issues/859
[PR]: https://github.com/swcarpentry/bc/pull/639
[discuss]: https://github.com/swcarpentry/lesson-template/blob/gh-pages/LAYOUT.md#discussion-page

**Comment by mlammens** [comment]
@jdblischak We don't have a discussion page setup in the repo yet, do we? Either way, I can submit a PR in the next day or two discussing this issue.

**Comment by jdblischak** [comment]
Thanks for volunteering, @mlammens. You are correct that we do not currently have a discussion.md, it is issue #16. Please feel free to add information on this topic as well as anything else that is relevant to teaching this lesson in a workshop.

**Comment by jdblischak** [comment]
Addressed by PR #61.
