### ISSUE TITLE
Episode ordering - stringsAsFactors discussed before Understanding Factors episode

### ISSUE THREAD

**Issue by elichad** [swcarpentry/r-novice-inflammation#584]
I've been following the lesson by myself. I'm new to R and I don't come from a data science background. On the whole, I've found it extremely useful, but there was one point at which I became confused.

I had never heard of factors before, and it was confusing to encounter them for the first time in episode 11 when discussing the [`stringsAsFactors` argument](http://swcarpentry.github.io/r-novice-inflammation/instructor/11-supp-read-write-csv.html#the-stringsasfactors-argument) to `read.csv`. I ended up Googling factors by myself, because I assumed I had missed something fundamental, only to find the information I was looking for later in episode 12.
The lesson would have flowed better for me if episode 12 (Understanding Factors) had come before episode 11.

I will open a PR to at least link to episode 12 from the `stringsAsFactors` section of episode 11, as that would have helped me.

**Comment by HaoZeke** [comment]
Thanks for the feedback and quick resolution via PR! I see it was merged, would you like to add more on factors or should this issue be closed for now?

**Comment by elichad** [comment]
I don't have more to add, so I'm okay with closing this.
