### ISSUE TITLE
Inaccurate maintainers list

### ISSUE THREAD

**Issue by quirksahern** [swcarpentry/r-novice-inflammation#596]
### What is the problem?

A mismatch between maintainers listed on SWC website and the repo ReadMe, please update.

requested on behalf of the SWC Lesson Programme Governance Committee

### Location of problem (optional)

ReadMe.md

**Comment by Bisaloo** [comment]
Thanks for raising this issue! On a related note, I see the following files that seem severely out of date. 

- [CITATION](https://github.com/swcarpentry/r-novice-inflammation/blob/main/CITATION)
- [AUTHORS](https://github.com/swcarpentry/r-novice-inflammation/blob/main/AUTHORS)


These files don't seem to be part of the current standard lesson infrastructure. Should they be removed?

**Comment by HaoZeke** [comment]
I mentioned this in private correspondence to some of my co-maintainers, but I'm of the opnion that both the `.mailmap` and the `AUTHORS` fie should be removed. CITATION should be replaced with a `.cff` file generate following [these instructions](https://docs.ropensci.org/cffr/) using `cffr`. We might as well also generate `codemeta` [via codemetar](https://docs.ropensci.org/codemetar/).

**Comment by HaoZeke** [comment]
@Bisaloo and @isaac-jennings also please add yourselves to the `readme` ^_^

**Comment by Bisaloo** [comment]
Linking to this more general discussion of a cff file for all carpentries lessons: https://github.com/carpentries/sandpaper/issues/508
