### ISSUE TITLE
suppy "ignore.case=TRUE" in callings of "sub" function 

### ISSUE THREAD

**Issue by HKYang** [swcarpentry/r-novice-inflammation#77]
I suggest to suppy "ignore.case=TRUE" in callings of "sub" function in the section entitled "Making choice" within R course material.

The R function "sub" is used there to substitute the filename ending "csv" with "pdf". In Windows platforms, since file names are case insensitive, users are free to use capital letters. Unfortunately, pattern strings in "sub" function are case sensitive by default. So, it is necessary to accomodate the scenario of having capital letters in file name extension by supplying the argument value of "ignore.case=TRUE".

**Comment by jdblischak** [comment]
Thanks for the suggestion, @HKYang.

Have you run into issues with this in a workshop?

In this specific instance, I don't think adding this argument is necessary. All the files use all lower case letters, and the students do not create the names themselves. They download the data as is, so I would be surprised if this were to cause an issue in a workshop.

In a bigger picture though, do we want to encourage Windows users to name their files in such a way? If they do want to name their files ".PDF", shouldn't the code they write explicitly reflect this, e.g. `sub("CSV", "PDF", f)`? I don't think we would want to encourage them to use a system of data management where they don't know what their filenames are.

Please let me know I misunderstood your suggestion.

**Comment by HKYang** [comment]
Hi, John:
I agree with you that in workshops very unlikely this issue will be popped
up.
However, this is more about fault-tolerance in good programming practices
that we are supposed to teach in addition to programming skills.
Thanks for your attention.
-kai
